/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao;


import com.merchant.dao.tables.FeeCalBatch;
import com.merchant.dao.tables.FeeCalBillingSnapshot;
import com.merchant.dao.tables.FeeCalFundInstruction;
import com.merchant.dao.tables.FeeCalMerchant;
import com.merchant.dao.tables.FeeCalTermDef;
import com.merchant.dao.tables.FeeCalTermInst;
import com.merchant.dao.tables.FeeCalTermInstAlloc;
import com.merchant.dao.tables.FlywaySchemaHistory;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1065224520;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * 费用清算批次表
     */
    public final FeeCalBatch FEE_CAL_BATCH = FeeCalBatch.FEE_CAL_BATCH;

    /**
     * 清算账单视图快照
     */
    public final FeeCalBillingSnapshot FEE_CAL_BILLING_SNAPSHOT = FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT;

    /**
     * 资金指令表
     */
    public final FeeCalFundInstruction FEE_CAL_FUND_INSTRUCTION = FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION;

    /**
     * 清算主体表
     */
    public final FeeCalMerchant FEE_CAL_MERCHANT = FeeCalMerchant.FEE_CAL_MERCHANT;

    /**
     * 费用项定义表
     */
    public final FeeCalTermDef FEE_CAL_TERM_DEF = FeeCalTermDef.FEE_CAL_TERM_DEF;

    /**
     * 费用项实例表
     */
    public final FeeCalTermInst FEE_CAL_TERM_INST = FeeCalTermInst.FEE_CAL_TERM_INST;

    /**
     * 费用项账单分配
     */
    public final FeeCalTermInstAlloc FEE_CAL_TERM_INST_ALLOC = FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FeeCalBatch.FEE_CAL_BATCH,
            FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT,
            FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION,
            FeeCalMerchant.FEE_CAL_MERCHANT,
            FeeCalTermDef.FEE_CAL_TERM_DEF,
            FeeCalTermInst.FEE_CAL_TERM_INST,
            FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }
}
