/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao;


import com.merchant.dao.tables.FeeCalBillingSnapshot;
import com.merchant.dao.tables.FeeCalFundInstruction;
import com.merchant.dao.tables.FeeCalMerchant;
import com.merchant.dao.tables.FeeCalTermInst;
import com.merchant.dao.tables.FeeCalTermInstAlloc;
import com.merchant.dao.tables.FlywaySchemaHistory;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM = Indexes0.FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM;
    public static final Index FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM_KEY = Indexes0.FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM_KEY;
    public static final Index FEE_CAL_FUND_INSTRUCTION_IDX_BATCH_NO = Indexes0.FEE_CAL_FUND_INSTRUCTION_IDX_BATCH_NO;
    public static final Index FEE_CAL_FUND_INSTRUCTION_IDX_FUND_STATUS = Indexes0.FEE_CAL_FUND_INSTRUCTION_IDX_FUND_STATUS;
    public static final Index FEE_CAL_FUND_INSTRUCTION_IDX_TERM_INST = Indexes0.FEE_CAL_FUND_INSTRUCTION_IDX_TERM_INST;
    public static final Index FEE_CAL_MERCHANT_IDX_BATCH_NO = Indexes0.FEE_CAL_MERCHANT_IDX_BATCH_NO;
    public static final Index FEE_CAL_TERM_INST_IDX_BATCH_NO_MERCHANT = Indexes0.FEE_CAL_TERM_INST_IDX_BATCH_NO_MERCHANT;
    public static final Index FEE_CAL_TERM_INST_IDX_TERM_CODE = Indexes0.FEE_CAL_TERM_INST_IDX_TERM_CODE;
    public static final Index FEE_CAL_TERM_INST_ALLOC_IDX_BATCH_TERM = Indexes0.FEE_CAL_TERM_INST_ALLOC_IDX_BATCH_TERM;
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM = Internal.createIndex("idx_billing_batch_term", FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT, new OrderField[] { FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BATCH_NO, FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.TERM_CODE }, false);
        public static Index FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM_KEY = Internal.createIndex("idx_billing_batch_term_key", FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT, new OrderField[] { FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BATCH_NO, FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.TERM_CODE, FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BILLING_KEY }, false);
        public static Index FEE_CAL_FUND_INSTRUCTION_IDX_BATCH_NO = Internal.createIndex("idx_batch_no", FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION, new OrderField[] { FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.BATCH_NO }, false);
        public static Index FEE_CAL_FUND_INSTRUCTION_IDX_FUND_STATUS = Internal.createIndex("idx_fund_status", FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION, new OrderField[] { FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_STATUS }, false);
        public static Index FEE_CAL_FUND_INSTRUCTION_IDX_TERM_INST = Internal.createIndex("idx_term_inst", FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION, new OrderField[] { FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.TERM_INST_ID }, false);
        public static Index FEE_CAL_MERCHANT_IDX_BATCH_NO = Internal.createIndex("idx_batch_no", FeeCalMerchant.FEE_CAL_MERCHANT, new OrderField[] { FeeCalMerchant.FEE_CAL_MERCHANT.BATCH_NO }, false);
        public static Index FEE_CAL_TERM_INST_IDX_BATCH_NO_MERCHANT = Internal.createIndex("idx_batch_no_merchant", FeeCalTermInst.FEE_CAL_TERM_INST, new OrderField[] { FeeCalTermInst.FEE_CAL_TERM_INST.BATCH_NO, FeeCalTermInst.FEE_CAL_TERM_INST.MERCHANT_ID }, false);
        public static Index FEE_CAL_TERM_INST_IDX_TERM_CODE = Internal.createIndex("idx_term_code", FeeCalTermInst.FEE_CAL_TERM_INST, new OrderField[] { FeeCalTermInst.FEE_CAL_TERM_INST.TERM_CODE }, false);
        public static Index FEE_CAL_TERM_INST_ALLOC_IDX_BATCH_TERM = Internal.createIndex("idx_batch_term", FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC, new OrderField[] { FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.BATCH_NO, FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.TERM_CODE }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    }
}
