/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao;


import com.merchant.dao.tables.FeeCalBatch;
import com.merchant.dao.tables.FeeCalBillingSnapshot;
import com.merchant.dao.tables.FeeCalFundInstruction;
import com.merchant.dao.tables.FeeCalMerchant;
import com.merchant.dao.tables.FeeCalTermDef;
import com.merchant.dao.tables.FeeCalTermInst;
import com.merchant.dao.tables.FeeCalTermInstAlloc;
import com.merchant.dao.tables.FlywaySchemaHistory;
import com.merchant.dao.tables.records.FeeCalBatchRecord;
import com.merchant.dao.tables.records.FeeCalBillingSnapshotRecord;
import com.merchant.dao.tables.records.FeeCalFundInstructionRecord;
import com.merchant.dao.tables.records.FeeCalMerchantRecord;
import com.merchant.dao.tables.records.FeeCalTermDefRecord;
import com.merchant.dao.tables.records.FeeCalTermInstAllocRecord;
import com.merchant.dao.tables.records.FeeCalTermInstRecord;
import com.merchant.dao.tables.records.FlywaySchemaHistoryRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<FeeCalBatchRecord, Long> IDENTITY_FEE_CAL_BATCH = Identities0.IDENTITY_FEE_CAL_BATCH;
    public static final Identity<FeeCalBillingSnapshotRecord, Long> IDENTITY_FEE_CAL_BILLING_SNAPSHOT = Identities0.IDENTITY_FEE_CAL_BILLING_SNAPSHOT;
    public static final Identity<FeeCalFundInstructionRecord, Long> IDENTITY_FEE_CAL_FUND_INSTRUCTION = Identities0.IDENTITY_FEE_CAL_FUND_INSTRUCTION;
    public static final Identity<FeeCalMerchantRecord, Long> IDENTITY_FEE_CAL_MERCHANT = Identities0.IDENTITY_FEE_CAL_MERCHANT;
    public static final Identity<FeeCalTermInstRecord, Long> IDENTITY_FEE_CAL_TERM_INST = Identities0.IDENTITY_FEE_CAL_TERM_INST;
    public static final Identity<FeeCalTermInstAllocRecord, Long> IDENTITY_FEE_CAL_TERM_INST_ALLOC = Identities0.IDENTITY_FEE_CAL_TERM_INST_ALLOC;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FeeCalBatchRecord> KEY_FEE_CAL_BATCH_PRIMARY = UniqueKeys0.KEY_FEE_CAL_BATCH_PRIMARY;
    public static final UniqueKey<FeeCalBatchRecord> KEY_FEE_CAL_BATCH_UK_BATCH_NO = UniqueKeys0.KEY_FEE_CAL_BATCH_UK_BATCH_NO;
    public static final UniqueKey<FeeCalBillingSnapshotRecord> KEY_FEE_CAL_BILLING_SNAPSHOT_PRIMARY = UniqueKeys0.KEY_FEE_CAL_BILLING_SNAPSHOT_PRIMARY;
    public static final UniqueKey<FeeCalFundInstructionRecord> KEY_FEE_CAL_FUND_INSTRUCTION_PRIMARY = UniqueKeys0.KEY_FEE_CAL_FUND_INSTRUCTION_PRIMARY;
    public static final UniqueKey<FeeCalFundInstructionRecord> KEY_FEE_CAL_FUND_INSTRUCTION_UK_BATCH_TERM_BIZ = UniqueKeys0.KEY_FEE_CAL_FUND_INSTRUCTION_UK_BATCH_TERM_BIZ;
    public static final UniqueKey<FeeCalMerchantRecord> KEY_FEE_CAL_MERCHANT_PRIMARY = UniqueKeys0.KEY_FEE_CAL_MERCHANT_PRIMARY;
    public static final UniqueKey<FeeCalTermDefRecord> KEY_FEE_CAL_TERM_DEF_PRIMARY = UniqueKeys0.KEY_FEE_CAL_TERM_DEF_PRIMARY;
    public static final UniqueKey<FeeCalTermInstRecord> KEY_FEE_CAL_TERM_INST_PRIMARY = UniqueKeys0.KEY_FEE_CAL_TERM_INST_PRIMARY;
    public static final UniqueKey<FeeCalTermInstAllocRecord> KEY_FEE_CAL_TERM_INST_ALLOC_PRIMARY = UniqueKeys0.KEY_FEE_CAL_TERM_INST_ALLOC_PRIMARY;
    public static final UniqueKey<FeeCalTermInstAllocRecord> KEY_FEE_CAL_TERM_INST_ALLOC_UK_TERM_SNAPSHOT = UniqueKeys0.KEY_FEE_CAL_TERM_INST_ALLOC_UK_TERM_SNAPSHOT;
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<FeeCalBatchRecord, Long> IDENTITY_FEE_CAL_BATCH = Internal.createIdentity(FeeCalBatch.FEE_CAL_BATCH, FeeCalBatch.FEE_CAL_BATCH.ID);
        public static Identity<FeeCalBillingSnapshotRecord, Long> IDENTITY_FEE_CAL_BILLING_SNAPSHOT = Internal.createIdentity(FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT, FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.ID);
        public static Identity<FeeCalFundInstructionRecord, Long> IDENTITY_FEE_CAL_FUND_INSTRUCTION = Internal.createIdentity(FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION, FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.ID);
        public static Identity<FeeCalMerchantRecord, Long> IDENTITY_FEE_CAL_MERCHANT = Internal.createIdentity(FeeCalMerchant.FEE_CAL_MERCHANT, FeeCalMerchant.FEE_CAL_MERCHANT.ID);
        public static Identity<FeeCalTermInstRecord, Long> IDENTITY_FEE_CAL_TERM_INST = Internal.createIdentity(FeeCalTermInst.FEE_CAL_TERM_INST, FeeCalTermInst.FEE_CAL_TERM_INST.ID);
        public static Identity<FeeCalTermInstAllocRecord, Long> IDENTITY_FEE_CAL_TERM_INST_ALLOC = Internal.createIdentity(FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC, FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FeeCalBatchRecord> KEY_FEE_CAL_BATCH_PRIMARY = Internal.createUniqueKey(FeeCalBatch.FEE_CAL_BATCH, "KEY_fee_cal_batch_PRIMARY", new TableField[] { FeeCalBatch.FEE_CAL_BATCH.ID }, true);
        public static final UniqueKey<FeeCalBatchRecord> KEY_FEE_CAL_BATCH_UK_BATCH_NO = Internal.createUniqueKey(FeeCalBatch.FEE_CAL_BATCH, "KEY_fee_cal_batch_uk_batch_no", new TableField[] { FeeCalBatch.FEE_CAL_BATCH.BATCH_NO }, true);
        public static final UniqueKey<FeeCalBillingSnapshotRecord> KEY_FEE_CAL_BILLING_SNAPSHOT_PRIMARY = Internal.createUniqueKey(FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT, "KEY_fee_cal_billing_snapshot_PRIMARY", new TableField[] { FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.ID }, true);
        public static final UniqueKey<FeeCalFundInstructionRecord> KEY_FEE_CAL_FUND_INSTRUCTION_PRIMARY = Internal.createUniqueKey(FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION, "KEY_fee_cal_fund_instruction_PRIMARY", new TableField[] { FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.ID }, true);
        public static final UniqueKey<FeeCalFundInstructionRecord> KEY_FEE_CAL_FUND_INSTRUCTION_UK_BATCH_TERM_BIZ = Internal.createUniqueKey(FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION, "KEY_fee_cal_fund_instruction_uk_batch_term_biz", new TableField[] { FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.BATCH_NO, FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.TERM_INST_ID, FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_BIZ_TYPE }, true);
        public static final UniqueKey<FeeCalMerchantRecord> KEY_FEE_CAL_MERCHANT_PRIMARY = Internal.createUniqueKey(FeeCalMerchant.FEE_CAL_MERCHANT, "KEY_fee_cal_merchant_PRIMARY", new TableField[] { FeeCalMerchant.FEE_CAL_MERCHANT.ID }, true);
        public static final UniqueKey<FeeCalTermDefRecord> KEY_FEE_CAL_TERM_DEF_PRIMARY = Internal.createUniqueKey(FeeCalTermDef.FEE_CAL_TERM_DEF, "KEY_fee_cal_term_def_PRIMARY", new TableField[] { FeeCalTermDef.FEE_CAL_TERM_DEF.CODE }, true);
        public static final UniqueKey<FeeCalTermInstRecord> KEY_FEE_CAL_TERM_INST_PRIMARY = Internal.createUniqueKey(FeeCalTermInst.FEE_CAL_TERM_INST, "KEY_fee_cal_term_inst_PRIMARY", new TableField[] { FeeCalTermInst.FEE_CAL_TERM_INST.ID }, true);
        public static final UniqueKey<FeeCalTermInstAllocRecord> KEY_FEE_CAL_TERM_INST_ALLOC_PRIMARY = Internal.createUniqueKey(FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC, "KEY_fee_cal_term_inst_alloc_PRIMARY", new TableField[] { FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.ID }, true);
        public static final UniqueKey<FeeCalTermInstAllocRecord> KEY_FEE_CAL_TERM_INST_ALLOC_UK_TERM_SNAPSHOT = Internal.createUniqueKey(FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC, "KEY_fee_cal_term_inst_alloc_uk_term_snapshot", new TableField[] { FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.TERM_INST_ID, FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.BILLING_SNAPSHOT_ID }, true);
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    }
}
