/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao;


import com.merchant.dao.tables.FeeCalBatch;
import com.merchant.dao.tables.FeeCalBillingSnapshot;
import com.merchant.dao.tables.FeeCalFundInstruction;
import com.merchant.dao.tables.FeeCalMerchant;
import com.merchant.dao.tables.FeeCalTermDef;
import com.merchant.dao.tables.FeeCalTermInst;
import com.merchant.dao.tables.FeeCalTermInstAlloc;
import com.merchant.dao.tables.FlywaySchemaHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 费用清算批次表
     */
    public static final FeeCalBatch FEE_CAL_BATCH = FeeCalBatch.FEE_CAL_BATCH;

    /**
     * 清算账单视图快照
     */
    public static final FeeCalBillingSnapshot FEE_CAL_BILLING_SNAPSHOT = FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT;

    /**
     * 资金指令表
     */
    public static final FeeCalFundInstruction FEE_CAL_FUND_INSTRUCTION = FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION;

    /**
     * 清算主体表
     */
    public static final FeeCalMerchant FEE_CAL_MERCHANT = FeeCalMerchant.FEE_CAL_MERCHANT;

    /**
     * 费用项定义表
     */
    public static final FeeCalTermDef FEE_CAL_TERM_DEF = FeeCalTermDef.FEE_CAL_TERM_DEF;

    /**
     * 费用项实例表
     */
    public static final FeeCalTermInst FEE_CAL_TERM_INST = FeeCalTermInst.FEE_CAL_TERM_INST;

    /**
     * 费用项账单分配
     */
    public static final FeeCalTermInstAlloc FEE_CAL_TERM_INST_ALLOC = FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
