/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalMerchant;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 清算主体表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalMerchantRecord extends UpdatableRecordImpl<FeeCalMerchantRecord> implements Record7<Long, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1623048121;

    /**
     * Setter for <code>fee_cal_merchant.id</code>.
     */
    public FeeCalMerchantRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fee_cal_merchant.batch_no</code>. 清算批次号
     */
    public FeeCalMerchantRecord setBatchNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.batch_no</code>. 清算批次号
     */
    public String getBatchNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_merchant.merchant_type</code>. 主体类型
     */
    public FeeCalMerchantRecord setMerchantType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.merchant_type</code>. 主体类型
     */
    public String getMerchantType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fee_cal_merchant.merchant_code</code>. 主体编码
     */
    public FeeCalMerchantRecord setMerchantCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.merchant_code</code>. 主体编码
     */
    public String getMerchantCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fee_cal_merchant.deposit_account_id</code>. 保证金账户ID（预留）
     */
    public FeeCalMerchantRecord setDepositAccountId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.deposit_account_id</code>. 保证金账户ID（预留）
     */
    public String getDepositAccountId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fee_cal_merchant.ctime</code>.
     */
    public FeeCalMerchantRecord setCtime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>fee_cal_merchant.mtime</code>.
     */
    public FeeCalMerchantRecord setMtime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_merchant.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.ID;
    }

    @Override
    public Field<String> field2() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.BATCH_NO;
    }

    @Override
    public Field<String> field3() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.MERCHANT_TYPE;
    }

    @Override
    public Field<String> field4() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.MERCHANT_CODE;
    }

    @Override
    public Field<String> field5() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.DEPOSIT_ACCOUNT_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.CTIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return FeeCalMerchant.FEE_CAL_MERCHANT.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBatchNo();
    }

    @Override
    public String component3() {
        return getMerchantType();
    }

    @Override
    public String component4() {
        return getMerchantCode();
    }

    @Override
    public String component5() {
        return getDepositAccountId();
    }

    @Override
    public LocalDateTime component6() {
        return getCtime();
    }

    @Override
    public LocalDateTime component7() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBatchNo();
    }

    @Override
    public String value3() {
        return getMerchantType();
    }

    @Override
    public String value4() {
        return getMerchantCode();
    }

    @Override
    public String value5() {
        return getDepositAccountId();
    }

    @Override
    public LocalDateTime value6() {
        return getCtime();
    }

    @Override
    public LocalDateTime value7() {
        return getMtime();
    }

    @Override
    public FeeCalMerchantRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord value2(String value) {
        setBatchNo(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord value3(String value) {
        setMerchantType(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord value4(String value) {
        setMerchantCode(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord value5(String value) {
        setDepositAccountId(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord value6(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord value7(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FeeCalMerchantRecord values(Long value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalMerchantRecord
     */
    public FeeCalMerchantRecord() {
        super(FeeCalMerchant.FEE_CAL_MERCHANT);
    }

    /**
     * Create a detached, initialised FeeCalMerchantRecord
     */
    public FeeCalMerchantRecord(Long id, String batchNo, String merchantType, String merchantCode, String depositAccountId, LocalDateTime ctime, LocalDateTime mtime) {
        super(FeeCalMerchant.FEE_CAL_MERCHANT);

        set(0, id);
        set(1, batchNo);
        set(2, merchantType);
        set(3, merchantCode);
        set(4, depositAccountId);
        set(5, ctime);
        set(6, mtime);
    }
}
