/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalBillingSnapshot;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 清算账单视图快照
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalBillingSnapshotRecord extends UpdatableRecordImpl<FeeCalBillingSnapshotRecord> implements Record9<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, JSON, LocalDateTime> {

    private static final long serialVersionUID = 994291940;

    /**
     * Setter for <code>fee_cal_billing_snapshot.id</code>. 主键ID
     */
    public FeeCalBillingSnapshotRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.batch_no</code>. 清算批次号
     */
    public FeeCalBillingSnapshotRecord setBatchNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.batch_no</code>. 清算批次号
     */
    public String getBatchNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.term_code</code>. 费用项 code
     */
    public FeeCalBillingSnapshotRecord setTermCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.term_code</code>. 费用项 code
     */
    public String getTermCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.billing_key</code>. 上游账单可读标识
     */
    public FeeCalBillingSnapshotRecord setBillingKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.billing_key</code>. 上游账单可读标识
     */
    public String getBillingKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.billing_should_pay_amount</code>. 应付金额
     */
    public FeeCalBillingSnapshotRecord setBillingShouldPayAmount(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.billing_should_pay_amount</code>. 应付金额
     */
    public BigDecimal getBillingShouldPayAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.billing_actual_pay_amount</code>. 已付金额
     */
    public FeeCalBillingSnapshotRecord setBillingActualPayAmount(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.billing_actual_pay_amount</code>. 已付金额
     */
    public BigDecimal getBillingActualPayAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.billing_unpaid_amount</code>. 未付金额（应付-已付）
     */
    public FeeCalBillingSnapshotRecord setBillingUnpaidAmount(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.billing_unpaid_amount</code>. 未付金额（应付-已付）
     */
    public BigDecimal getBillingUnpaidAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.billing_source_info</code>. 上游账单原始JSON
     */
    public FeeCalBillingSnapshotRecord setBillingSourceInfo(JSON value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.billing_source_info</code>. 上游账单原始JSON
     */
    public JSON getBillingSourceInfo() {
        return (JSON) get(7);
    }

    /**
     * Setter for <code>fee_cal_billing_snapshot.snapshot_time</code>. 快照时间
     */
    public FeeCalBillingSnapshotRecord setSnapshotTime(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_billing_snapshot.snapshot_time</code>. 快照时间
     */
    public LocalDateTime getSnapshotTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, JSON, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, JSON, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.ID;
    }

    @Override
    public Field<String> field2() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BATCH_NO;
    }

    @Override
    public Field<String> field3() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.TERM_CODE;
    }

    @Override
    public Field<String> field4() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BILLING_KEY;
    }

    @Override
    public Field<BigDecimal> field5() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BILLING_SHOULD_PAY_AMOUNT;
    }

    @Override
    public Field<BigDecimal> field6() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BILLING_ACTUAL_PAY_AMOUNT;
    }

    @Override
    public Field<BigDecimal> field7() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BILLING_UNPAID_AMOUNT;
    }

    @Override
    public Field<JSON> field8() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.BILLING_SOURCE_INFO;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT.SNAPSHOT_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBatchNo();
    }

    @Override
    public String component3() {
        return getTermCode();
    }

    @Override
    public String component4() {
        return getBillingKey();
    }

    @Override
    public BigDecimal component5() {
        return getBillingShouldPayAmount();
    }

    @Override
    public BigDecimal component6() {
        return getBillingActualPayAmount();
    }

    @Override
    public BigDecimal component7() {
        return getBillingUnpaidAmount();
    }

    @Override
    public JSON component8() {
        return getBillingSourceInfo();
    }

    @Override
    public LocalDateTime component9() {
        return getSnapshotTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBatchNo();
    }

    @Override
    public String value3() {
        return getTermCode();
    }

    @Override
    public String value4() {
        return getBillingKey();
    }

    @Override
    public BigDecimal value5() {
        return getBillingShouldPayAmount();
    }

    @Override
    public BigDecimal value6() {
        return getBillingActualPayAmount();
    }

    @Override
    public BigDecimal value7() {
        return getBillingUnpaidAmount();
    }

    @Override
    public JSON value8() {
        return getBillingSourceInfo();
    }

    @Override
    public LocalDateTime value9() {
        return getSnapshotTime();
    }

    @Override
    public FeeCalBillingSnapshotRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value2(String value) {
        setBatchNo(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value3(String value) {
        setTermCode(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value4(String value) {
        setBillingKey(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value5(BigDecimal value) {
        setBillingShouldPayAmount(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value6(BigDecimal value) {
        setBillingActualPayAmount(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value7(BigDecimal value) {
        setBillingUnpaidAmount(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value8(JSON value) {
        setBillingSourceInfo(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord value9(LocalDateTime value) {
        setSnapshotTime(value);
        return this;
    }

    @Override
    public FeeCalBillingSnapshotRecord values(Long value1, String value2, String value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, JSON value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalBillingSnapshotRecord
     */
    public FeeCalBillingSnapshotRecord() {
        super(FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT);
    }

    /**
     * Create a detached, initialised FeeCalBillingSnapshotRecord
     */
    public FeeCalBillingSnapshotRecord(Long id, String batchNo, String termCode, String billingKey, BigDecimal billingShouldPayAmount, BigDecimal billingActualPayAmount, BigDecimal billingUnpaidAmount, JSON billingSourceInfo, LocalDateTime snapshotTime) {
        super(FeeCalBillingSnapshot.FEE_CAL_BILLING_SNAPSHOT);

        set(0, id);
        set(1, batchNo);
        set(2, termCode);
        set(3, billingKey);
        set(4, billingShouldPayAmount);
        set(5, billingActualPayAmount);
        set(6, billingUnpaidAmount);
        set(7, billingSourceInfo);
        set(8, snapshotTime);
    }
}
