/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalBatch;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 费用清算批次表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalBatchRecord extends UpdatableRecordImpl<FeeCalBatchRecord> implements Record11<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = -1934686387;

    /**
     * Setter for <code>fee_cal_batch.id</code>.
     */
    public FeeCalBatchRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fee_cal_batch.batch_no</code>. 清算批次号
     */
    public FeeCalBatchRecord setBatchNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.batch_no</code>. 清算批次号
     */
    public String getBatchNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_batch.status</code>. 状态: EDITING / DONE
     */
    public FeeCalBatchRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.status</code>. 状态: EDITING / DONE
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fee_cal_batch.billing_data_status</code>. 账单同步状态: PENDING / LOADING / READY / FAILED
     */
    public FeeCalBatchRecord setBillingDataStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.billing_data_status</code>. 账单同步状态: PENDING / LOADING / READY / FAILED
     */
    public String getBillingDataStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fee_cal_batch.deposit_balance_total</code>. 初始保证金余额（用户输入）
     */
    public FeeCalBatchRecord setDepositBalanceTotal(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.deposit_balance_total</code>. 初始保证金余额（用户输入）
     */
    public BigDecimal getDepositBalanceTotal() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>fee_cal_batch.deposit_amount_deduct</code>. 本次抵扣金额总和
     */
    public FeeCalBatchRecord setDepositAmountDeduct(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.deposit_amount_deduct</code>. 本次抵扣金额总和
     */
    public BigDecimal getDepositAmountDeduct() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>fee_cal_batch.deposit_balance_remain</code>. 清算后剩余保证金（计算得出）
     */
    public FeeCalBatchRecord setDepositBalanceRemain(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.deposit_balance_remain</code>. 清算后剩余保证金（计算得出）
     */
    public BigDecimal getDepositBalanceRemain() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>fee_cal_batch.unpaid_amount_remain</code>. 抵扣后剩余欠付金额（仍需支付）
     */
    public FeeCalBatchRecord setUnpaidAmountRemain(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.unpaid_amount_remain</code>. 抵扣后剩余欠付金额（仍需支付）
     */
    public BigDecimal getUnpaidAmountRemain() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>fee_cal_batch.ctime</code>.
     */
    public FeeCalBatchRecord setCtime(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>fee_cal_batch.mtime</code>.
     */
    public FeeCalBatchRecord setMtime(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>fee_cal_batch.request_id</code>. 幂等请求ID
     */
    public FeeCalBatchRecord setRequestId(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_batch.request_id</code>. 幂等请求ID
     */
    public String getRequestId() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeeCalBatch.FEE_CAL_BATCH.ID;
    }

    @Override
    public Field<String> field2() {
        return FeeCalBatch.FEE_CAL_BATCH.BATCH_NO;
    }

    @Override
    public Field<String> field3() {
        return FeeCalBatch.FEE_CAL_BATCH.STATUS;
    }

    @Override
    public Field<String> field4() {
        return FeeCalBatch.FEE_CAL_BATCH.BILLING_DATA_STATUS;
    }

    @Override
    public Field<BigDecimal> field5() {
        return FeeCalBatch.FEE_CAL_BATCH.DEPOSIT_BALANCE_TOTAL;
    }

    @Override
    public Field<BigDecimal> field6() {
        return FeeCalBatch.FEE_CAL_BATCH.DEPOSIT_AMOUNT_DEDUCT;
    }

    @Override
    public Field<BigDecimal> field7() {
        return FeeCalBatch.FEE_CAL_BATCH.DEPOSIT_BALANCE_REMAIN;
    }

    @Override
    public Field<BigDecimal> field8() {
        return FeeCalBatch.FEE_CAL_BATCH.UNPAID_AMOUNT_REMAIN;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return FeeCalBatch.FEE_CAL_BATCH.CTIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return FeeCalBatch.FEE_CAL_BATCH.MTIME;
    }

    @Override
    public Field<String> field11() {
        return FeeCalBatch.FEE_CAL_BATCH.REQUEST_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBatchNo();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getBillingDataStatus();
    }

    @Override
    public BigDecimal component5() {
        return getDepositBalanceTotal();
    }

    @Override
    public BigDecimal component6() {
        return getDepositAmountDeduct();
    }

    @Override
    public BigDecimal component7() {
        return getDepositBalanceRemain();
    }

    @Override
    public BigDecimal component8() {
        return getUnpaidAmountRemain();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public LocalDateTime component10() {
        return getMtime();
    }

    @Override
    public String component11() {
        return getRequestId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBatchNo();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getBillingDataStatus();
    }

    @Override
    public BigDecimal value5() {
        return getDepositBalanceTotal();
    }

    @Override
    public BigDecimal value6() {
        return getDepositAmountDeduct();
    }

    @Override
    public BigDecimal value7() {
        return getDepositBalanceRemain();
    }

    @Override
    public BigDecimal value8() {
        return getUnpaidAmountRemain();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public LocalDateTime value10() {
        return getMtime();
    }

    @Override
    public String value11() {
        return getRequestId();
    }

    @Override
    public FeeCalBatchRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value2(String value) {
        setBatchNo(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value4(String value) {
        setBillingDataStatus(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value5(BigDecimal value) {
        setDepositBalanceTotal(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value6(BigDecimal value) {
        setDepositAmountDeduct(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value7(BigDecimal value) {
        setDepositBalanceRemain(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value8(BigDecimal value) {
        setUnpaidAmountRemain(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value10(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord value11(String value) {
        setRequestId(value);
        return this;
    }

    @Override
    public FeeCalBatchRecord values(Long value1, String value2, String value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, LocalDateTime value9, LocalDateTime value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalBatchRecord
     */
    public FeeCalBatchRecord() {
        super(FeeCalBatch.FEE_CAL_BATCH);
    }

    /**
     * Create a detached, initialised FeeCalBatchRecord
     */
    public FeeCalBatchRecord(Long id, String batchNo, String status, String billingDataStatus, BigDecimal depositBalanceTotal, BigDecimal depositAmountDeduct, BigDecimal depositBalanceRemain, BigDecimal unpaidAmountRemain, LocalDateTime ctime, LocalDateTime mtime, String requestId) {
        super(FeeCalBatch.FEE_CAL_BATCH);

        set(0, id);
        set(1, batchNo);
        set(2, status);
        set(3, billingDataStatus);
        set(4, depositBalanceTotal);
        set(5, depositAmountDeduct);
        set(6, depositBalanceRemain);
        set(7, unpaidAmountRemain);
        set(8, ctime);
        set(9, mtime);
        set(10, requestId);
    }
}
