/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalTermDef;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 费用项定义表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermDefRecord extends UpdatableRecordImpl<FeeCalTermDefRecord> implements Record8<String, String, Integer, Byte, Byte, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 155520229;

    /**
     * Setter for <code>fee_cal_term_def.code</code>. 费用项 code（主键）
     */
    public FeeCalTermDefRecord setCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.code</code>. 费用项 code（主键）
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>fee_cal_term_def.name</code>. 费用项名称
     */
    public FeeCalTermDefRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.name</code>. 费用项名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_term_def.sort_no</code>. 展示顺序
     */
    public FeeCalTermDefRecord setSortNo(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.sort_no</code>. 展示顺序
     */
    public Integer getSortNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fee_cal_term_def.enabled</code>. 是否启用: 1 启用 / 0 停用
     */
    public FeeCalTermDefRecord setEnabled(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.enabled</code>. 是否启用: 1 启用 / 0 停用
     */
    public Byte getEnabled() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>fee_cal_term_def.auto_load</code>. 是否自动拉账填充
     */
    public FeeCalTermDefRecord setAutoLoad(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.auto_load</code>. 是否自动拉账填充
     */
    public Byte getAutoLoad() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>fee_cal_term_def.bill_alloc_enabled</code>. 是否开启账单分配
     */
    public FeeCalTermDefRecord setBillAllocEnabled(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.bill_alloc_enabled</code>. 是否开启账单分配
     */
    public Integer getBillAllocEnabled() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>fee_cal_term_def.ctime</code>.
     */
    public FeeCalTermDefRecord setCtime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>fee_cal_term_def.mtime</code>.
     */
    public FeeCalTermDefRecord setMtime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_def.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, Integer, Byte, Byte, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, Integer, Byte, Byte, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.CODE;
    }

    @Override
    public Field<String> field2() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.SORT_NO;
    }

    @Override
    public Field<Byte> field4() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.ENABLED;
    }

    @Override
    public Field<Byte> field5() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.AUTO_LOAD;
    }

    @Override
    public Field<Integer> field6() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.BILL_ALLOC_ENABLED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.CTIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return FeeCalTermDef.FEE_CAL_TERM_DEF.MTIME;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getSortNo();
    }

    @Override
    public Byte component4() {
        return getEnabled();
    }

    @Override
    public Byte component5() {
        return getAutoLoad();
    }

    @Override
    public Integer component6() {
        return getBillAllocEnabled();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public LocalDateTime component8() {
        return getMtime();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getSortNo();
    }

    @Override
    public Byte value4() {
        return getEnabled();
    }

    @Override
    public Byte value5() {
        return getAutoLoad();
    }

    @Override
    public Integer value6() {
        return getBillAllocEnabled();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public LocalDateTime value8() {
        return getMtime();
    }

    @Override
    public FeeCalTermDefRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value3(Integer value) {
        setSortNo(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value4(Byte value) {
        setEnabled(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value5(Byte value) {
        setAutoLoad(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value6(Integer value) {
        setBillAllocEnabled(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord value8(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FeeCalTermDefRecord values(String value1, String value2, Integer value3, Byte value4, Byte value5, Integer value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalTermDefRecord
     */
    public FeeCalTermDefRecord() {
        super(FeeCalTermDef.FEE_CAL_TERM_DEF);
    }

    /**
     * Create a detached, initialised FeeCalTermDefRecord
     */
    public FeeCalTermDefRecord(String code, String name, Integer sortNo, Byte enabled, Byte autoLoad, Integer billAllocEnabled, LocalDateTime ctime, LocalDateTime mtime) {
        super(FeeCalTermDef.FEE_CAL_TERM_DEF);

        set(0, code);
        set(1, name);
        set(2, sortNo);
        set(3, enabled);
        set(4, autoLoad);
        set(5, billAllocEnabled);
        set(6, ctime);
        set(7, mtime);
    }
}
