/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalTermInstAlloc;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 费用项账单分配
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermInstAllocRecord extends UpdatableRecordImpl<FeeCalTermInstAllocRecord> implements Record10<Long, String, Long, String, Long, BigDecimal, Integer, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -458303272;

    /**
     * Setter for <code>fee_cal_term_inst_alloc.id</code>. 主键
     */
    public FeeCalTermInstAllocRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.batch_no</code>. 批次号
     */
    public FeeCalTermInstAllocRecord setBatchNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.batch_no</code>. 批次号
     */
    public String getBatchNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.term_inst_id</code>. 费用项实例ID
     */
    public FeeCalTermInstAllocRecord setTermInstId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.term_inst_id</code>. 费用项实例ID
     */
    public Long getTermInstId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.term_code</code>. 费用项编码
     */
    public FeeCalTermInstAllocRecord setTermCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.term_code</code>. 费用项编码
     */
    public String getTermCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.billing_snapshot_id</code>. 快照ID
     */
    public FeeCalTermInstAllocRecord setBillingSnapshotId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.billing_snapshot_id</code>. 快照ID
     */
    public Long getBillingSnapshotId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.unpaid_amount</code>. 账单未付金额
     */
    public FeeCalTermInstAllocRecord setUnpaidAmount(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.unpaid_amount</code>. 账单未付金额
     */
    public BigDecimal getUnpaidAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.alloc_flag</code>. 是否抵扣
     */
    public FeeCalTermInstAllocRecord setAllocFlag(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.alloc_flag</code>. 是否抵扣
     */
    public Integer getAllocFlag() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.alloc_amount</code>. 抵扣金额
     */
    public FeeCalTermInstAllocRecord setAllocAmount(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.alloc_amount</code>. 抵扣金额
     */
    public BigDecimal getAllocAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.created_at</code>.
     */
    public FeeCalTermInstAllocRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>fee_cal_term_inst_alloc.updated_at</code>.
     */
    public FeeCalTermInstAllocRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst_alloc.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, Long, String, Long, BigDecimal, Integer, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, Long, String, Long, BigDecimal, Integer, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.ID;
    }

    @Override
    public Field<String> field2() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.BATCH_NO;
    }

    @Override
    public Field<Long> field3() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.TERM_INST_ID;
    }

    @Override
    public Field<String> field4() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.TERM_CODE;
    }

    @Override
    public Field<Long> field5() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.BILLING_SNAPSHOT_ID;
    }

    @Override
    public Field<BigDecimal> field6() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.UNPAID_AMOUNT;
    }

    @Override
    public Field<Integer> field7() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.ALLOC_FLAG;
    }

    @Override
    public Field<BigDecimal> field8() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.ALLOC_AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBatchNo();
    }

    @Override
    public Long component3() {
        return getTermInstId();
    }

    @Override
    public String component4() {
        return getTermCode();
    }

    @Override
    public Long component5() {
        return getBillingSnapshotId();
    }

    @Override
    public BigDecimal component6() {
        return getUnpaidAmount();
    }

    @Override
    public Integer component7() {
        return getAllocFlag();
    }

    @Override
    public BigDecimal component8() {
        return getAllocAmount();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBatchNo();
    }

    @Override
    public Long value3() {
        return getTermInstId();
    }

    @Override
    public String value4() {
        return getTermCode();
    }

    @Override
    public Long value5() {
        return getBillingSnapshotId();
    }

    @Override
    public BigDecimal value6() {
        return getUnpaidAmount();
    }

    @Override
    public Integer value7() {
        return getAllocFlag();
    }

    @Override
    public BigDecimal value8() {
        return getAllocAmount();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdatedAt();
    }

    @Override
    public FeeCalTermInstAllocRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value2(String value) {
        setBatchNo(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value3(Long value) {
        setTermInstId(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value4(String value) {
        setTermCode(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value5(Long value) {
        setBillingSnapshotId(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value6(BigDecimal value) {
        setUnpaidAmount(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value7(Integer value) {
        setAllocFlag(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value8(BigDecimal value) {
        setAllocAmount(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord value10(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FeeCalTermInstAllocRecord values(Long value1, String value2, Long value3, String value4, Long value5, BigDecimal value6, Integer value7, BigDecimal value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalTermInstAllocRecord
     */
    public FeeCalTermInstAllocRecord() {
        super(FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC);
    }

    /**
     * Create a detached, initialised FeeCalTermInstAllocRecord
     */
    public FeeCalTermInstAllocRecord(Long id, String batchNo, Long termInstId, String termCode, Long billingSnapshotId, BigDecimal unpaidAmount, Integer allocFlag, BigDecimal allocAmount, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FeeCalTermInstAlloc.FEE_CAL_TERM_INST_ALLOC);

        set(0, id);
        set(1, batchNo);
        set(2, termInstId);
        set(3, termCode);
        set(4, billingSnapshotId);
        set(5, unpaidAmount);
        set(6, allocFlag);
        set(7, allocAmount);
        set(8, createdAt);
        set(9, updatedAt);
    }
}
