/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalFundInstruction;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 资金指令表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalFundInstructionRecord extends UpdatableRecordImpl<FeeCalFundInstructionRecord> implements Record22<Long, String, Long, String, String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, JSON, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -139433090;

    /**
     * Setter for <code>fee_cal_fund_instruction.id</code>. 指令主键ID
     */
    public FeeCalFundInstructionRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.id</code>. 指令主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.batch_no</code>. 清算批次编号
     */
    public FeeCalFundInstructionRecord setBatchNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.batch_no</code>. 清算批次编号
     */
    public String getBatchNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.term_inst_id</code>. 来源费用项ID；整体退款可为空
     */
    public FeeCalFundInstructionRecord setTermInstId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.term_inst_id</code>. 来源费用项ID；整体退款可为空
     */
    public Long getTermInstId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.settle_subject_type</code>. 清算主体类型
     */
    public FeeCalFundInstructionRecord setSettleSubjectType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.settle_subject_type</code>. 清算主体类型
     */
    public String getSettleSubjectType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.settle_subject_no</code>. 清算主体编码
     */
    public FeeCalFundInstructionRecord setSettleSubjectNo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.settle_subject_no</code>. 清算主体编码
     */
    public String getSettleSubjectNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.payer_type</code>. 付款方类型
     */
    public FeeCalFundInstructionRecord setPayerType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.payer_type</code>. 付款方类型
     */
    public String getPayerType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.payer_no</code>. 付款方编码
     */
    public FeeCalFundInstructionRecord setPayerNo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.payer_no</code>. 付款方编码
     */
    public String getPayerNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.payee_type</code>. 收款方类型
     */
    public FeeCalFundInstructionRecord setPayeeType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.payee_type</code>. 收款方类型
     */
    public String getPayeeType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.payee_no</code>. 收款方编码
     */
    public FeeCalFundInstructionRecord setPayeeNo(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.payee_no</code>. 收款方编码
     */
    public String getPayeeNo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.fund_direction</code>. DEBIT/CREDIT/COLLECT
     */
    public FeeCalFundInstructionRecord setFundDirection(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.fund_direction</code>. DEBIT/CREDIT/COLLECT
     */
    public String getFundDirection() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.fund_biz_type</code>. DEPOSIT_DEDUCT/DEPOSIT_REFUND
     */
    public FeeCalFundInstructionRecord setFundBizType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.fund_biz_type</code>. DEPOSIT_DEDUCT/DEPOSIT_REFUND
     */
    public String getFundBizType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.account_type</code>. 账户类型
     */
    public FeeCalFundInstructionRecord setAccountType(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.account_type</code>. 账户类型
     */
    public String getAccountType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.should_amount</code>. 应执行金额
     */
    public FeeCalFundInstructionRecord setShouldAmount(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.should_amount</code>. 应执行金额
     */
    public BigDecimal getShouldAmount() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.actual_amount</code>. 实际执行金额
     */
    public FeeCalFundInstructionRecord setActualAmount(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.actual_amount</code>. 实际执行金额
     */
    public BigDecimal getActualAmount() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.fund_status</code>. PENDING/EXECUTING/SUCCESS/FAIL
     */
    public FeeCalFundInstructionRecord setFundStatus(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.fund_status</code>. PENDING/EXECUTING/SUCCESS/FAIL
     */
    public String getFundStatus() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.callback_status</code>. NOT_STARTED/DOING/SUCCESS/FAIL
     */
    public FeeCalFundInstructionRecord setCallbackStatus(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.callback_status</code>. NOT_STARTED/DOING/SUCCESS/FAIL
     */
    public String getCallbackStatus() {
        return (String) get(15);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.fund_order_id</code>. 资金系统单号
     */
    public FeeCalFundInstructionRecord setFundOrderId(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.fund_order_id</code>. 资金系统单号
     */
    public String getFundOrderId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.fund_channel</code>. 资金渠道
     */
    public FeeCalFundInstructionRecord setFundChannel(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.fund_channel</code>. 资金渠道
     */
    public String getFundChannel() {
        return (String) get(17);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.fund_order_info</code>. 资金单详情JSON
     */
    public FeeCalFundInstructionRecord setFundOrderInfo(JSON value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.fund_order_info</code>. 资金单详情JSON
     */
    public JSON getFundOrderInfo() {
        return (JSON) get(18);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.attachment_ids</code>. 附件ID集合
     */
    public FeeCalFundInstructionRecord setAttachmentIds(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.attachment_ids</code>. 附件ID集合
     */
    public String getAttachmentIds() {
        return (String) get(19);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.created_at</code>.
     */
    public FeeCalFundInstructionRecord setCreatedAt(LocalDateTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>fee_cal_fund_instruction.updated_at</code>.
     */
    public FeeCalFundInstructionRecord setUpdatedAt(LocalDateTime value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_fund_instruction.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, String, Long, String, String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, JSON, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<Long, String, Long, String, String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, JSON, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.ID;
    }

    @Override
    public Field<String> field2() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.BATCH_NO;
    }

    @Override
    public Field<Long> field3() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.TERM_INST_ID;
    }

    @Override
    public Field<String> field4() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.SETTLE_SUBJECT_TYPE;
    }

    @Override
    public Field<String> field5() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.SETTLE_SUBJECT_NO;
    }

    @Override
    public Field<String> field6() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.PAYER_TYPE;
    }

    @Override
    public Field<String> field7() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.PAYER_NO;
    }

    @Override
    public Field<String> field8() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.PAYEE_TYPE;
    }

    @Override
    public Field<String> field9() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.PAYEE_NO;
    }

    @Override
    public Field<String> field10() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_DIRECTION;
    }

    @Override
    public Field<String> field11() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_BIZ_TYPE;
    }

    @Override
    public Field<String> field12() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.ACCOUNT_TYPE;
    }

    @Override
    public Field<BigDecimal> field13() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.SHOULD_AMOUNT;
    }

    @Override
    public Field<BigDecimal> field14() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.ACTUAL_AMOUNT;
    }

    @Override
    public Field<String> field15() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_STATUS;
    }

    @Override
    public Field<String> field16() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.CALLBACK_STATUS;
    }

    @Override
    public Field<String> field17() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_ORDER_ID;
    }

    @Override
    public Field<String> field18() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_CHANNEL;
    }

    @Override
    public Field<JSON> field19() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.FUND_ORDER_INFO;
    }

    @Override
    public Field<String> field20() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.ATTACHMENT_IDS;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field22() {
        return FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBatchNo();
    }

    @Override
    public Long component3() {
        return getTermInstId();
    }

    @Override
    public String component4() {
        return getSettleSubjectType();
    }

    @Override
    public String component5() {
        return getSettleSubjectNo();
    }

    @Override
    public String component6() {
        return getPayerType();
    }

    @Override
    public String component7() {
        return getPayerNo();
    }

    @Override
    public String component8() {
        return getPayeeType();
    }

    @Override
    public String component9() {
        return getPayeeNo();
    }

    @Override
    public String component10() {
        return getFundDirection();
    }

    @Override
    public String component11() {
        return getFundBizType();
    }

    @Override
    public String component12() {
        return getAccountType();
    }

    @Override
    public BigDecimal component13() {
        return getShouldAmount();
    }

    @Override
    public BigDecimal component14() {
        return getActualAmount();
    }

    @Override
    public String component15() {
        return getFundStatus();
    }

    @Override
    public String component16() {
        return getCallbackStatus();
    }

    @Override
    public String component17() {
        return getFundOrderId();
    }

    @Override
    public String component18() {
        return getFundChannel();
    }

    @Override
    public JSON component19() {
        return getFundOrderInfo();
    }

    @Override
    public String component20() {
        return getAttachmentIds();
    }

    @Override
    public LocalDateTime component21() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component22() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBatchNo();
    }

    @Override
    public Long value3() {
        return getTermInstId();
    }

    @Override
    public String value4() {
        return getSettleSubjectType();
    }

    @Override
    public String value5() {
        return getSettleSubjectNo();
    }

    @Override
    public String value6() {
        return getPayerType();
    }

    @Override
    public String value7() {
        return getPayerNo();
    }

    @Override
    public String value8() {
        return getPayeeType();
    }

    @Override
    public String value9() {
        return getPayeeNo();
    }

    @Override
    public String value10() {
        return getFundDirection();
    }

    @Override
    public String value11() {
        return getFundBizType();
    }

    @Override
    public String value12() {
        return getAccountType();
    }

    @Override
    public BigDecimal value13() {
        return getShouldAmount();
    }

    @Override
    public BigDecimal value14() {
        return getActualAmount();
    }

    @Override
    public String value15() {
        return getFundStatus();
    }

    @Override
    public String value16() {
        return getCallbackStatus();
    }

    @Override
    public String value17() {
        return getFundOrderId();
    }

    @Override
    public String value18() {
        return getFundChannel();
    }

    @Override
    public JSON value19() {
        return getFundOrderInfo();
    }

    @Override
    public String value20() {
        return getAttachmentIds();
    }

    @Override
    public LocalDateTime value21() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value22() {
        return getUpdatedAt();
    }

    @Override
    public FeeCalFundInstructionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value2(String value) {
        setBatchNo(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value3(Long value) {
        setTermInstId(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value4(String value) {
        setSettleSubjectType(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value5(String value) {
        setSettleSubjectNo(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value6(String value) {
        setPayerType(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value7(String value) {
        setPayerNo(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value8(String value) {
        setPayeeType(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value9(String value) {
        setPayeeNo(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value10(String value) {
        setFundDirection(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value11(String value) {
        setFundBizType(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value12(String value) {
        setAccountType(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value13(BigDecimal value) {
        setShouldAmount(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value14(BigDecimal value) {
        setActualAmount(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value15(String value) {
        setFundStatus(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value16(String value) {
        setCallbackStatus(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value17(String value) {
        setFundOrderId(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value18(String value) {
        setFundChannel(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value19(JSON value) {
        setFundOrderInfo(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value20(String value) {
        setAttachmentIds(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value21(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord value22(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FeeCalFundInstructionRecord values(Long value1, String value2, Long value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, BigDecimal value13, BigDecimal value14, String value15, String value16, String value17, String value18, JSON value19, String value20, LocalDateTime value21, LocalDateTime value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalFundInstructionRecord
     */
    public FeeCalFundInstructionRecord() {
        super(FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION);
    }

    /**
     * Create a detached, initialised FeeCalFundInstructionRecord
     */
    public FeeCalFundInstructionRecord(Long id, String batchNo, Long termInstId, String settleSubjectType, String settleSubjectNo, String payerType, String payerNo, String payeeType, String payeeNo, String fundDirection, String fundBizType, String accountType, BigDecimal shouldAmount, BigDecimal actualAmount, String fundStatus, String callbackStatus, String fundOrderId, String fundChannel, JSON fundOrderInfo, String attachmentIds, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FeeCalFundInstruction.FEE_CAL_FUND_INSTRUCTION);

        set(0, id);
        set(1, batchNo);
        set(2, termInstId);
        set(3, settleSubjectType);
        set(4, settleSubjectNo);
        set(5, payerType);
        set(6, payerNo);
        set(7, payeeType);
        set(8, payeeNo);
        set(9, fundDirection);
        set(10, fundBizType);
        set(11, accountType);
        set(12, shouldAmount);
        set(13, actualAmount);
        set(14, fundStatus);
        set(15, callbackStatus);
        set(16, fundOrderId);
        set(17, fundChannel);
        set(18, fundOrderInfo);
        set(19, attachmentIds);
        set(20, createdAt);
        set(21, updatedAt);
    }
}
