/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.records;


import com.merchant.dao.tables.FeeCalTermInst;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 费用项实例表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermInstRecord extends UpdatableRecordImpl<FeeCalTermInstRecord> implements Record12<Long, String, Long, String, String, BigDecimal, Byte, BigDecimal, Byte, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1850703149;

    /**
     * Setter for <code>fee_cal_term_inst.id</code>.
     */
    public FeeCalTermInstRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fee_cal_term_inst.batch_no</code>. 清算批次号
     */
    public FeeCalTermInstRecord setBatchNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.batch_no</code>. 清算批次号
     */
    public String getBatchNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fee_cal_term_inst.merchant_id</code>. 清算主体ID
     */
    public FeeCalTermInstRecord setMerchantId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.merchant_id</code>. 清算主体ID
     */
    public Long getMerchantId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fee_cal_term_inst.term_code</code>. 费用项 code
     */
    public FeeCalTermInstRecord setTermCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.term_code</code>. 费用项 code
     */
    public String getTermCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fee_cal_term_inst.status</code>. 状态: PENDING / DRAFT / DONE
     */
    public FeeCalTermInstRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.status</code>. 状态: PENDING / DRAFT / DONE
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fee_cal_term_inst.unpaid_amount</code>. 欠付金额
     */
    public FeeCalTermInstRecord setUnpaidAmount(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.unpaid_amount</code>. 欠付金额
     */
    public BigDecimal getUnpaidAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>fee_cal_term_inst.deduct_flag</code>. 是否抵扣: 0 否 / 1 是
     */
    public FeeCalTermInstRecord setDeductFlag(Byte value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.deduct_flag</code>. 是否抵扣: 0 否 / 1 是
     */
    public Byte getDeductFlag() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>fee_cal_term_inst.deduct_amount</code>. 抵扣金额
     */
    public FeeCalTermInstRecord setDeductAmount(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.deduct_amount</code>. 抵扣金额
     */
    public BigDecimal getDeductAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>fee_cal_term_inst.auto_load</code>. 是否来自自动拉账
     */
    public FeeCalTermInstRecord setAutoLoad(Byte value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.auto_load</code>. 是否来自自动拉账
     */
    public Byte getAutoLoad() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>fee_cal_term_inst.billing_alloc_enabled</code>. 是否开启账单分配
     */
    public FeeCalTermInstRecord setBillingAllocEnabled(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.billing_alloc_enabled</code>. 是否开启账单分配
     */
    public Integer getBillingAllocEnabled() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>fee_cal_term_inst.ctime</code>.
     */
    public FeeCalTermInstRecord setCtime(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>fee_cal_term_inst.mtime</code>.
     */
    public FeeCalTermInstRecord setMtime(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>fee_cal_term_inst.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, Long, String, String, BigDecimal, Byte, BigDecimal, Byte, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, Long, String, String, BigDecimal, Byte, BigDecimal, Byte, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.ID;
    }

    @Override
    public Field<String> field2() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.BATCH_NO;
    }

    @Override
    public Field<Long> field3() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.MERCHANT_ID;
    }

    @Override
    public Field<String> field4() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.TERM_CODE;
    }

    @Override
    public Field<String> field5() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.STATUS;
    }

    @Override
    public Field<BigDecimal> field6() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.UNPAID_AMOUNT;
    }

    @Override
    public Field<Byte> field7() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.DEDUCT_FLAG;
    }

    @Override
    public Field<BigDecimal> field8() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.DEDUCT_AMOUNT;
    }

    @Override
    public Field<Byte> field9() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.AUTO_LOAD;
    }

    @Override
    public Field<Integer> field10() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.BILLING_ALLOC_ENABLED;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.CTIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return FeeCalTermInst.FEE_CAL_TERM_INST.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBatchNo();
    }

    @Override
    public Long component3() {
        return getMerchantId();
    }

    @Override
    public String component4() {
        return getTermCode();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public BigDecimal component6() {
        return getUnpaidAmount();
    }

    @Override
    public Byte component7() {
        return getDeductFlag();
    }

    @Override
    public BigDecimal component8() {
        return getDeductAmount();
    }

    @Override
    public Byte component9() {
        return getAutoLoad();
    }

    @Override
    public Integer component10() {
        return getBillingAllocEnabled();
    }

    @Override
    public LocalDateTime component11() {
        return getCtime();
    }

    @Override
    public LocalDateTime component12() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBatchNo();
    }

    @Override
    public Long value3() {
        return getMerchantId();
    }

    @Override
    public String value4() {
        return getTermCode();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public BigDecimal value6() {
        return getUnpaidAmount();
    }

    @Override
    public Byte value7() {
        return getDeductFlag();
    }

    @Override
    public BigDecimal value8() {
        return getDeductAmount();
    }

    @Override
    public Byte value9() {
        return getAutoLoad();
    }

    @Override
    public Integer value10() {
        return getBillingAllocEnabled();
    }

    @Override
    public LocalDateTime value11() {
        return getCtime();
    }

    @Override
    public LocalDateTime value12() {
        return getMtime();
    }

    @Override
    public FeeCalTermInstRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value2(String value) {
        setBatchNo(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value3(Long value) {
        setMerchantId(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value4(String value) {
        setTermCode(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value6(BigDecimal value) {
        setUnpaidAmount(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value7(Byte value) {
        setDeductFlag(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value8(BigDecimal value) {
        setDeductAmount(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value9(Byte value) {
        setAutoLoad(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value10(Integer value) {
        setBillingAllocEnabled(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value11(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord value12(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FeeCalTermInstRecord values(Long value1, String value2, Long value3, String value4, String value5, BigDecimal value6, Byte value7, BigDecimal value8, Byte value9, Integer value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeeCalTermInstRecord
     */
    public FeeCalTermInstRecord() {
        super(FeeCalTermInst.FEE_CAL_TERM_INST);
    }

    /**
     * Create a detached, initialised FeeCalTermInstRecord
     */
    public FeeCalTermInstRecord(Long id, String batchNo, Long merchantId, String termCode, String status, BigDecimal unpaidAmount, Byte deductFlag, BigDecimal deductAmount, Byte autoLoad, Integer billingAllocEnabled, LocalDateTime ctime, LocalDateTime mtime) {
        super(FeeCalTermInst.FEE_CAL_TERM_INST);

        set(0, id);
        set(1, batchNo);
        set(2, merchantId);
        set(3, termCode);
        set(4, status);
        set(5, unpaidAmount);
        set(6, deductFlag);
        set(7, deductAmount);
        set(8, autoLoad);
        set(9, billingAllocEnabled);
        set(10, ctime);
        set(11, mtime);
    }
}
