/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalTermDefRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 费用项定义表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermDef extends TableImpl<FeeCalTermDefRecord> {

    private static final long serialVersionUID = 988096141;

    /**
     * The reference instance of <code>fee_cal_term_def</code>
     */
    public static final FeeCalTermDef FEE_CAL_TERM_DEF = new FeeCalTermDef();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalTermDefRecord> getRecordType() {
        return FeeCalTermDefRecord.class;
    }

    /**
     * The column <code>fee_cal_term_def.code</code>. 费用项 code（主键）
     */
    public final TableField<FeeCalTermDefRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "费用项 code（主键）");

    /**
     * The column <code>fee_cal_term_def.name</code>. 费用项名称
     */
    public final TableField<FeeCalTermDefRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "费用项名称");

    /**
     * The column <code>fee_cal_term_def.sort_no</code>. 展示顺序
     */
    public final TableField<FeeCalTermDefRecord, Integer> SORT_NO = createField(DSL.name("sort_no"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "展示顺序");

    /**
     * The column <code>fee_cal_term_def.enabled</code>. 是否启用: 1 启用 / 0 停用
     */
    public final TableField<FeeCalTermDefRecord, Byte> ENABLED = createField(DSL.name("enabled"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "是否启用: 1 启用 / 0 停用");

    /**
     * The column <code>fee_cal_term_def.auto_load</code>. 是否自动拉账填充
     */
    public final TableField<FeeCalTermDefRecord, Byte> AUTO_LOAD = createField(DSL.name("auto_load"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否自动拉账填充");

    /**
     * The column <code>fee_cal_term_def.bill_alloc_enabled</code>. 是否开启账单分配
     */
    public final TableField<FeeCalTermDefRecord, Integer> BILL_ALLOC_ENABLED = createField(DSL.name("bill_alloc_enabled"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否开启账单分配");

    /**
     * The column <code>fee_cal_term_def.ctime</code>.
     */
    public final TableField<FeeCalTermDefRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_term_def.mtime</code>.
     */
    public final TableField<FeeCalTermDefRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>fee_cal_term_def</code> table reference
     */
    public FeeCalTermDef() {
        this(DSL.name("fee_cal_term_def"), null);
    }

    /**
     * Create an aliased <code>fee_cal_term_def</code> table reference
     */
    public FeeCalTermDef(String alias) {
        this(DSL.name(alias), FEE_CAL_TERM_DEF);
    }

    /**
     * Create an aliased <code>fee_cal_term_def</code> table reference
     */
    public FeeCalTermDef(Name alias) {
        this(alias, FEE_CAL_TERM_DEF);
    }

    private FeeCalTermDef(Name alias, Table<FeeCalTermDefRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalTermDef(Name alias, Table<FeeCalTermDefRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("费用项定义表"), TableOptions.table());
    }

    public <O extends Record> FeeCalTermDef(Table<O> child, ForeignKey<O, FeeCalTermDefRecord> key) {
        super(child, key, FEE_CAL_TERM_DEF);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<FeeCalTermDefRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_TERM_DEF_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalTermDefRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalTermDefRecord>>asList(Keys.KEY_FEE_CAL_TERM_DEF_PRIMARY);
    }

    @Override
    public FeeCalTermDef as(String alias) {
        return new FeeCalTermDef(DSL.name(alias), this);
    }

    @Override
    public FeeCalTermDef as(Name alias) {
        return new FeeCalTermDef(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalTermDef rename(String name) {
        return new FeeCalTermDef(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalTermDef rename(Name name) {
        return new FeeCalTermDef(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, Integer, Byte, Byte, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
