/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Indexes;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalTermInstRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 费用项实例表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermInst extends TableImpl<FeeCalTermInstRecord> {

    private static final long serialVersionUID = -144352165;

    /**
     * The reference instance of <code>fee_cal_term_inst</code>
     */
    public static final FeeCalTermInst FEE_CAL_TERM_INST = new FeeCalTermInst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalTermInstRecord> getRecordType() {
        return FeeCalTermInstRecord.class;
    }

    /**
     * The column <code>fee_cal_term_inst.id</code>.
     */
    public final TableField<FeeCalTermInstRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fee_cal_term_inst.batch_no</code>. 清算批次号
     */
    public final TableField<FeeCalTermInstRecord, String> BATCH_NO = createField(DSL.name("batch_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "清算批次号");

    /**
     * The column <code>fee_cal_term_inst.merchant_id</code>. 清算主体ID
     */
    public final TableField<FeeCalTermInstRecord, Long> MERCHANT_ID = createField(DSL.name("merchant_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "清算主体ID");

    /**
     * The column <code>fee_cal_term_inst.term_code</code>. 费用项 code
     */
    public final TableField<FeeCalTermInstRecord, String> TERM_CODE = createField(DSL.name("term_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "费用项 code");

    /**
     * The column <code>fee_cal_term_inst.status</code>. 状态: PENDING / DRAFT / DONE
     */
    public final TableField<FeeCalTermInstRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("PENDING", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态: PENDING / DRAFT / DONE");

    /**
     * The column <code>fee_cal_term_inst.unpaid_amount</code>. 欠付金额
     */
    public final TableField<FeeCalTermInstRecord, BigDecimal> UNPAID_AMOUNT = createField(DSL.name("unpaid_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "欠付金额");

    /**
     * The column <code>fee_cal_term_inst.deduct_flag</code>. 是否抵扣: 0 否 / 1 是
     */
    public final TableField<FeeCalTermInstRecord, Byte> DEDUCT_FLAG = createField(DSL.name("deduct_flag"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否抵扣: 0 否 / 1 是");

    /**
     * The column <code>fee_cal_term_inst.deduct_amount</code>. 抵扣金额
     */
    public final TableField<FeeCalTermInstRecord, BigDecimal> DEDUCT_AMOUNT = createField(DSL.name("deduct_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "抵扣金额");

    /**
     * The column <code>fee_cal_term_inst.auto_load</code>. 是否来自自动拉账
     */
    public final TableField<FeeCalTermInstRecord, Byte> AUTO_LOAD = createField(DSL.name("auto_load"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否来自自动拉账");

    /**
     * The column <code>fee_cal_term_inst.billing_alloc_enabled</code>. 是否开启账单分配
     */
    public final TableField<FeeCalTermInstRecord, Integer> BILLING_ALLOC_ENABLED = createField(DSL.name("billing_alloc_enabled"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否开启账单分配");

    /**
     * The column <code>fee_cal_term_inst.ctime</code>.
     */
    public final TableField<FeeCalTermInstRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_term_inst.mtime</code>.
     */
    public final TableField<FeeCalTermInstRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>fee_cal_term_inst</code> table reference
     */
    public FeeCalTermInst() {
        this(DSL.name("fee_cal_term_inst"), null);
    }

    /**
     * Create an aliased <code>fee_cal_term_inst</code> table reference
     */
    public FeeCalTermInst(String alias) {
        this(DSL.name(alias), FEE_CAL_TERM_INST);
    }

    /**
     * Create an aliased <code>fee_cal_term_inst</code> table reference
     */
    public FeeCalTermInst(Name alias) {
        this(alias, FEE_CAL_TERM_INST);
    }

    private FeeCalTermInst(Name alias, Table<FeeCalTermInstRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalTermInst(Name alias, Table<FeeCalTermInstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("费用项实例表"), TableOptions.table());
    }

    public <O extends Record> FeeCalTermInst(Table<O> child, ForeignKey<O, FeeCalTermInstRecord> key) {
        super(child, key, FEE_CAL_TERM_INST);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FEE_CAL_TERM_INST_IDX_BATCH_NO_MERCHANT, Indexes.FEE_CAL_TERM_INST_IDX_TERM_CODE);
    }

    @Override
    public Identity<FeeCalTermInstRecord, Long> getIdentity() {
        return Keys.IDENTITY_FEE_CAL_TERM_INST;
    }

    @Override
    public UniqueKey<FeeCalTermInstRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_TERM_INST_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalTermInstRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalTermInstRecord>>asList(Keys.KEY_FEE_CAL_TERM_INST_PRIMARY);
    }

    @Override
    public FeeCalTermInst as(String alias) {
        return new FeeCalTermInst(DSL.name(alias), this);
    }

    @Override
    public FeeCalTermInst as(Name alias) {
        return new FeeCalTermInst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalTermInst rename(String name) {
        return new FeeCalTermInst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalTermInst rename(Name name) {
        return new FeeCalTermInst(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, Long, String, String, BigDecimal, Byte, BigDecimal, Byte, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
