/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Indexes;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalMerchantRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 清算主体表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalMerchant extends TableImpl<FeeCalMerchantRecord> {

    private static final long serialVersionUID = -995272241;

    /**
     * The reference instance of <code>fee_cal_merchant</code>
     */
    public static final FeeCalMerchant FEE_CAL_MERCHANT = new FeeCalMerchant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalMerchantRecord> getRecordType() {
        return FeeCalMerchantRecord.class;
    }

    /**
     * The column <code>fee_cal_merchant.id</code>.
     */
    public final TableField<FeeCalMerchantRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fee_cal_merchant.batch_no</code>. 清算批次号
     */
    public final TableField<FeeCalMerchantRecord, String> BATCH_NO = createField(DSL.name("batch_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "清算批次号");

    /**
     * The column <code>fee_cal_merchant.merchant_type</code>. 主体类型
     */
    public final TableField<FeeCalMerchantRecord, String> MERCHANT_TYPE = createField(DSL.name("merchant_type"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "主体类型");

    /**
     * The column <code>fee_cal_merchant.merchant_code</code>. 主体编码
     */
    public final TableField<FeeCalMerchantRecord, String> MERCHANT_CODE = createField(DSL.name("merchant_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "主体编码");

    /**
     * The column <code>fee_cal_merchant.deposit_account_id</code>. 保证金账户ID（预留）
     */
    public final TableField<FeeCalMerchantRecord, String> DEPOSIT_ACCOUNT_ID = createField(DSL.name("deposit_account_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "保证金账户ID（预留）");

    /**
     * The column <code>fee_cal_merchant.ctime</code>.
     */
    public final TableField<FeeCalMerchantRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_merchant.mtime</code>.
     */
    public final TableField<FeeCalMerchantRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>fee_cal_merchant</code> table reference
     */
    public FeeCalMerchant() {
        this(DSL.name("fee_cal_merchant"), null);
    }

    /**
     * Create an aliased <code>fee_cal_merchant</code> table reference
     */
    public FeeCalMerchant(String alias) {
        this(DSL.name(alias), FEE_CAL_MERCHANT);
    }

    /**
     * Create an aliased <code>fee_cal_merchant</code> table reference
     */
    public FeeCalMerchant(Name alias) {
        this(alias, FEE_CAL_MERCHANT);
    }

    private FeeCalMerchant(Name alias, Table<FeeCalMerchantRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalMerchant(Name alias, Table<FeeCalMerchantRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("清算主体表"), TableOptions.table());
    }

    public <O extends Record> FeeCalMerchant(Table<O> child, ForeignKey<O, FeeCalMerchantRecord> key) {
        super(child, key, FEE_CAL_MERCHANT);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FEE_CAL_MERCHANT_IDX_BATCH_NO);
    }

    @Override
    public Identity<FeeCalMerchantRecord, Long> getIdentity() {
        return Keys.IDENTITY_FEE_CAL_MERCHANT;
    }

    @Override
    public UniqueKey<FeeCalMerchantRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_MERCHANT_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalMerchantRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalMerchantRecord>>asList(Keys.KEY_FEE_CAL_MERCHANT_PRIMARY);
    }

    @Override
    public FeeCalMerchant as(String alias) {
        return new FeeCalMerchant(DSL.name(alias), this);
    }

    @Override
    public FeeCalMerchant as(Name alias) {
        return new FeeCalMerchant(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalMerchant rename(String name) {
        return new FeeCalMerchant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalMerchant rename(Name name) {
        return new FeeCalMerchant(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
