/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalBatchRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 费用清算批次表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalBatch extends TableImpl<FeeCalBatchRecord> {

    private static final long serialVersionUID = 2042228985;

    /**
     * The reference instance of <code>fee_cal_batch</code>
     */
    public static final FeeCalBatch FEE_CAL_BATCH = new FeeCalBatch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalBatchRecord> getRecordType() {
        return FeeCalBatchRecord.class;
    }

    /**
     * The column <code>fee_cal_batch.id</code>.
     */
    public final TableField<FeeCalBatchRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fee_cal_batch.batch_no</code>. 清算批次号
     */
    public final TableField<FeeCalBatchRecord, String> BATCH_NO = createField(DSL.name("batch_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "清算批次号");

    /**
     * The column <code>fee_cal_batch.status</code>. 状态: EDITING / DONE
     */
    public final TableField<FeeCalBatchRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("EDITING", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态: EDITING / DONE");

    /**
     * The column <code>fee_cal_batch.billing_data_status</code>. 账单同步状态: PENDING / LOADING / READY / FAILED
     */
    public final TableField<FeeCalBatchRecord, String> BILLING_DATA_STATUS = createField(DSL.name("billing_data_status"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("PENDING", org.jooq.impl.SQLDataType.VARCHAR)), this, "账单同步状态: PENDING / LOADING / READY / FAILED");

    /**
     * The column <code>fee_cal_batch.deposit_balance_total</code>. 初始保证金余额（用户输入）
     */
    public final TableField<FeeCalBatchRecord, BigDecimal> DEPOSIT_BALANCE_TOTAL = createField(DSL.name("deposit_balance_total"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "初始保证金余额（用户输入）");

    /**
     * The column <code>fee_cal_batch.deposit_amount_deduct</code>. 本次抵扣金额总和
     */
    public final TableField<FeeCalBatchRecord, BigDecimal> DEPOSIT_AMOUNT_DEDUCT = createField(DSL.name("deposit_amount_deduct"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "本次抵扣金额总和");

    /**
     * The column <code>fee_cal_batch.deposit_balance_remain</code>. 清算后剩余保证金（计算得出）
     */
    public final TableField<FeeCalBatchRecord, BigDecimal> DEPOSIT_BALANCE_REMAIN = createField(DSL.name("deposit_balance_remain"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "清算后剩余保证金（计算得出）");

    /**
     * The column <code>fee_cal_batch.unpaid_amount_remain</code>. 抵扣后剩余欠付金额（仍需支付）
     */
    public final TableField<FeeCalBatchRecord, BigDecimal> UNPAID_AMOUNT_REMAIN = createField(DSL.name("unpaid_amount_remain"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "抵扣后剩余欠付金额（仍需支付）");

    /**
     * The column <code>fee_cal_batch.ctime</code>.
     */
    public final TableField<FeeCalBatchRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_batch.mtime</code>.
     */
    public final TableField<FeeCalBatchRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_batch.request_id</code>. 幂等请求ID
     */
    public final TableField<FeeCalBatchRecord, String> REQUEST_ID = createField(DSL.name("request_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "幂等请求ID");

    /**
     * Create a <code>fee_cal_batch</code> table reference
     */
    public FeeCalBatch() {
        this(DSL.name("fee_cal_batch"), null);
    }

    /**
     * Create an aliased <code>fee_cal_batch</code> table reference
     */
    public FeeCalBatch(String alias) {
        this(DSL.name(alias), FEE_CAL_BATCH);
    }

    /**
     * Create an aliased <code>fee_cal_batch</code> table reference
     */
    public FeeCalBatch(Name alias) {
        this(alias, FEE_CAL_BATCH);
    }

    private FeeCalBatch(Name alias, Table<FeeCalBatchRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalBatch(Name alias, Table<FeeCalBatchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("费用清算批次表"), TableOptions.table());
    }

    public <O extends Record> FeeCalBatch(Table<O> child, ForeignKey<O, FeeCalBatchRecord> key) {
        super(child, key, FEE_CAL_BATCH);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FeeCalBatchRecord, Long> getIdentity() {
        return Keys.IDENTITY_FEE_CAL_BATCH;
    }

    @Override
    public UniqueKey<FeeCalBatchRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_BATCH_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalBatchRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalBatchRecord>>asList(Keys.KEY_FEE_CAL_BATCH_PRIMARY, Keys.KEY_FEE_CAL_BATCH_UK_BATCH_NO, Keys.KEY_FEE_CAL_BATCH_UK_REQUEST_ID);
    }

    @Override
    public FeeCalBatch as(String alias) {
        return new FeeCalBatch(DSL.name(alias), this);
    }

    @Override
    public FeeCalBatch as(Name alias) {
        return new FeeCalBatch(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalBatch rename(String name) {
        return new FeeCalBatch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalBatch rename(Name name) {
        return new FeeCalBatch(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
