/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Indexes;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalFundInstructionRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row22;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 资金指令表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalFundInstruction extends TableImpl<FeeCalFundInstructionRecord> {

    private static final long serialVersionUID = 1168276514;

    /**
     * The reference instance of <code>fee_cal_fund_instruction</code>
     */
    public static final FeeCalFundInstruction FEE_CAL_FUND_INSTRUCTION = new FeeCalFundInstruction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalFundInstructionRecord> getRecordType() {
        return FeeCalFundInstructionRecord.class;
    }

    /**
     * The column <code>fee_cal_fund_instruction.id</code>. 指令主键ID
     */
    public final TableField<FeeCalFundInstructionRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "指令主键ID");

    /**
     * The column <code>fee_cal_fund_instruction.batch_no</code>. 清算批次编号
     */
    public final TableField<FeeCalFundInstructionRecord, String> BATCH_NO = createField(DSL.name("batch_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "清算批次编号");

    /**
     * The column <code>fee_cal_fund_instruction.term_inst_id</code>. 来源费用项ID；整体退款可为空
     */
    public final TableField<FeeCalFundInstructionRecord, Long> TERM_INST_ID = createField(DSL.name("term_inst_id"), org.jooq.impl.SQLDataType.BIGINT, this, "来源费用项ID；整体退款可为空");

    /**
     * The column <code>fee_cal_fund_instruction.settle_subject_type</code>. 清算主体类型
     */
    public final TableField<FeeCalFundInstructionRecord, String> SETTLE_SUBJECT_TYPE = createField(DSL.name("settle_subject_type"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "清算主体类型");

    /**
     * The column <code>fee_cal_fund_instruction.settle_subject_no</code>. 清算主体编码
     */
    public final TableField<FeeCalFundInstructionRecord, String> SETTLE_SUBJECT_NO = createField(DSL.name("settle_subject_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "清算主体编码");

    /**
     * The column <code>fee_cal_fund_instruction.payer_type</code>. 付款方类型
     */
    public final TableField<FeeCalFundInstructionRecord, String> PAYER_TYPE = createField(DSL.name("payer_type"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "付款方类型");

    /**
     * The column <code>fee_cal_fund_instruction.payer_no</code>. 付款方编码
     */
    public final TableField<FeeCalFundInstructionRecord, String> PAYER_NO = createField(DSL.name("payer_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "付款方编码");

    /**
     * The column <code>fee_cal_fund_instruction.payee_type</code>. 收款方类型
     */
    public final TableField<FeeCalFundInstructionRecord, String> PAYEE_TYPE = createField(DSL.name("payee_type"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "收款方类型");

    /**
     * The column <code>fee_cal_fund_instruction.payee_no</code>. 收款方编码
     */
    public final TableField<FeeCalFundInstructionRecord, String> PAYEE_NO = createField(DSL.name("payee_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "收款方编码");

    /**
     * The column <code>fee_cal_fund_instruction.fund_direction</code>. DEBIT/CREDIT/COLLECT
     */
    public final TableField<FeeCalFundInstructionRecord, String> FUND_DIRECTION = createField(DSL.name("fund_direction"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "DEBIT/CREDIT/COLLECT");

    /**
     * The column <code>fee_cal_fund_instruction.fund_biz_type</code>. DEPOSIT_DEDUCT/DEPOSIT_REFUND
     */
    public final TableField<FeeCalFundInstructionRecord, String> FUND_BIZ_TYPE = createField(DSL.name("fund_biz_type"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "DEPOSIT_DEDUCT/DEPOSIT_REFUND");

    /**
     * The column <code>fee_cal_fund_instruction.account_type</code>. 账户类型
     */
    public final TableField<FeeCalFundInstructionRecord, String> ACCOUNT_TYPE = createField(DSL.name("account_type"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("DEPOSIT", org.jooq.impl.SQLDataType.VARCHAR)), this, "账户类型");

    /**
     * The column <code>fee_cal_fund_instruction.should_amount</code>. 应执行金额
     */
    public final TableField<FeeCalFundInstructionRecord, BigDecimal> SHOULD_AMOUNT = createField(DSL.name("should_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).nullable(false), this, "应执行金额");

    /**
     * The column <code>fee_cal_fund_instruction.actual_amount</code>. 实际执行金额
     */
    public final TableField<FeeCalFundInstructionRecord, BigDecimal> ACTUAL_AMOUNT = createField(DSL.name("actual_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2), this, "实际执行金额");

    /**
     * The column <code>fee_cal_fund_instruction.fund_status</code>. PENDING/EXECUTING/SUCCESS/FAIL
     */
    public final TableField<FeeCalFundInstructionRecord, String> FUND_STATUS = createField(DSL.name("fund_status"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "PENDING/EXECUTING/SUCCESS/FAIL");

    /**
     * The column <code>fee_cal_fund_instruction.callback_status</code>. NOT_STARTED/DOING/SUCCESS/FAIL
     */
    public final TableField<FeeCalFundInstructionRecord, String> CALLBACK_STATUS = createField(DSL.name("callback_status"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "NOT_STARTED/DOING/SUCCESS/FAIL");

    /**
     * The column <code>fee_cal_fund_instruction.fund_order_id</code>. 资金系统单号
     */
    public final TableField<FeeCalFundInstructionRecord, String> FUND_ORDER_ID = createField(DSL.name("fund_order_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "资金系统单号");

    /**
     * The column <code>fee_cal_fund_instruction.fund_channel</code>. 资金渠道
     */
    public final TableField<FeeCalFundInstructionRecord, String> FUND_CHANNEL = createField(DSL.name("fund_channel"), org.jooq.impl.SQLDataType.VARCHAR(32), this, "资金渠道");

    /**
     * The column <code>fee_cal_fund_instruction.fund_order_info</code>. 资金单详情JSON
     */
    public final TableField<FeeCalFundInstructionRecord, JSON> FUND_ORDER_INFO = createField(DSL.name("fund_order_info"), org.jooq.impl.SQLDataType.JSON, this, "资金单详情JSON");

    /**
     * The column <code>fee_cal_fund_instruction.attachment_ids</code>. 附件ID集合
     */
    public final TableField<FeeCalFundInstructionRecord, String> ATTACHMENT_IDS = createField(DSL.name("attachment_ids"), org.jooq.impl.SQLDataType.VARCHAR(512), this, "附件ID集合");

    /**
     * The column <code>fee_cal_fund_instruction.created_at</code>.
     */
    public final TableField<FeeCalFundInstructionRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_fund_instruction.updated_at</code>.
     */
    public final TableField<FeeCalFundInstructionRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>fee_cal_fund_instruction</code> table reference
     */
    public FeeCalFundInstruction() {
        this(DSL.name("fee_cal_fund_instruction"), null);
    }

    /**
     * Create an aliased <code>fee_cal_fund_instruction</code> table reference
     */
    public FeeCalFundInstruction(String alias) {
        this(DSL.name(alias), FEE_CAL_FUND_INSTRUCTION);
    }

    /**
     * Create an aliased <code>fee_cal_fund_instruction</code> table reference
     */
    public FeeCalFundInstruction(Name alias) {
        this(alias, FEE_CAL_FUND_INSTRUCTION);
    }

    private FeeCalFundInstruction(Name alias, Table<FeeCalFundInstructionRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalFundInstruction(Name alias, Table<FeeCalFundInstructionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("资金指令表"), TableOptions.table());
    }

    public <O extends Record> FeeCalFundInstruction(Table<O> child, ForeignKey<O, FeeCalFundInstructionRecord> key) {
        super(child, key, FEE_CAL_FUND_INSTRUCTION);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FEE_CAL_FUND_INSTRUCTION_IDX_BATCH_NO, Indexes.FEE_CAL_FUND_INSTRUCTION_IDX_FUND_STATUS, Indexes.FEE_CAL_FUND_INSTRUCTION_IDX_TERM_INST);
    }

    @Override
    public Identity<FeeCalFundInstructionRecord, Long> getIdentity() {
        return Keys.IDENTITY_FEE_CAL_FUND_INSTRUCTION;
    }

    @Override
    public UniqueKey<FeeCalFundInstructionRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_FUND_INSTRUCTION_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalFundInstructionRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalFundInstructionRecord>>asList(Keys.KEY_FEE_CAL_FUND_INSTRUCTION_PRIMARY, Keys.KEY_FEE_CAL_FUND_INSTRUCTION_UK_BATCH_TERM_BIZ);
    }

    @Override
    public FeeCalFundInstruction as(String alias) {
        return new FeeCalFundInstruction(DSL.name(alias), this);
    }

    @Override
    public FeeCalFundInstruction as(Name alias) {
        return new FeeCalFundInstruction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalFundInstruction rename(String name) {
        return new FeeCalFundInstruction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalFundInstruction rename(Name name) {
        return new FeeCalFundInstruction(name, null);
    }

    // -------------------------------------------------------------------------
    // Row22 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, String, Long, String, String, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, JSON, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row22) super.fieldsRow();
    }
}
