/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Indexes;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalBillingSnapshotRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 清算账单视图快照
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalBillingSnapshot extends TableImpl<FeeCalBillingSnapshotRecord> {

    private static final long serialVersionUID = -166404454;

    /**
     * The reference instance of <code>fee_cal_billing_snapshot</code>
     */
    public static final FeeCalBillingSnapshot FEE_CAL_BILLING_SNAPSHOT = new FeeCalBillingSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalBillingSnapshotRecord> getRecordType() {
        return FeeCalBillingSnapshotRecord.class;
    }

    /**
     * The column <code>fee_cal_billing_snapshot.id</code>. 主键ID
     */
    public final TableField<FeeCalBillingSnapshotRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>fee_cal_billing_snapshot.batch_no</code>. 清算批次号
     */
    public final TableField<FeeCalBillingSnapshotRecord, String> BATCH_NO = createField(DSL.name("batch_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "清算批次号");

    /**
     * The column <code>fee_cal_billing_snapshot.term_code</code>. 费用项 code
     */
    public final TableField<FeeCalBillingSnapshotRecord, String> TERM_CODE = createField(DSL.name("term_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "费用项 code");

    /**
     * The column <code>fee_cal_billing_snapshot.billing_key</code>. 上游账单可读标识
     */
    public final TableField<FeeCalBillingSnapshotRecord, String> BILLING_KEY = createField(DSL.name("billing_key"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "上游账单可读标识");

    /**
     * The column <code>fee_cal_billing_snapshot.billing_should_pay_amount</code>. 应付金额
     */
    public final TableField<FeeCalBillingSnapshotRecord, BigDecimal> BILLING_SHOULD_PAY_AMOUNT = createField(DSL.name("billing_should_pay_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "应付金额");

    /**
     * The column <code>fee_cal_billing_snapshot.billing_actual_pay_amount</code>. 已付金额
     */
    public final TableField<FeeCalBillingSnapshotRecord, BigDecimal> BILLING_ACTUAL_PAY_AMOUNT = createField(DSL.name("billing_actual_pay_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "已付金额");

    /**
     * The column <code>fee_cal_billing_snapshot.billing_unpaid_amount</code>. 未付金额（应付-已付）
     */
    public final TableField<FeeCalBillingSnapshotRecord, BigDecimal> BILLING_UNPAID_AMOUNT = createField(DSL.name("billing_unpaid_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "未付金额（应付-已付）");

    /**
     * The column <code>fee_cal_billing_snapshot.billing_source_info</code>. 上游账单原始JSON
     */
    public final TableField<FeeCalBillingSnapshotRecord, JSON> BILLING_SOURCE_INFO = createField(DSL.name("billing_source_info"), org.jooq.impl.SQLDataType.JSON, this, "上游账单原始JSON");

    /**
     * The column <code>fee_cal_billing_snapshot.snapshot_time</code>. 快照时间
     */
    public final TableField<FeeCalBillingSnapshotRecord, LocalDateTime> SNAPSHOT_TIME = createField(DSL.name("snapshot_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "快照时间");

    /**
     * Create a <code>fee_cal_billing_snapshot</code> table reference
     */
    public FeeCalBillingSnapshot() {
        this(DSL.name("fee_cal_billing_snapshot"), null);
    }

    /**
     * Create an aliased <code>fee_cal_billing_snapshot</code> table reference
     */
    public FeeCalBillingSnapshot(String alias) {
        this(DSL.name(alias), FEE_CAL_BILLING_SNAPSHOT);
    }

    /**
     * Create an aliased <code>fee_cal_billing_snapshot</code> table reference
     */
    public FeeCalBillingSnapshot(Name alias) {
        this(alias, FEE_CAL_BILLING_SNAPSHOT);
    }

    private FeeCalBillingSnapshot(Name alias, Table<FeeCalBillingSnapshotRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalBillingSnapshot(Name alias, Table<FeeCalBillingSnapshotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("清算账单视图快照"), TableOptions.table());
    }

    public <O extends Record> FeeCalBillingSnapshot(Table<O> child, ForeignKey<O, FeeCalBillingSnapshotRecord> key) {
        super(child, key, FEE_CAL_BILLING_SNAPSHOT);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM, Indexes.FEE_CAL_BILLING_SNAPSHOT_IDX_BILLING_BATCH_TERM_KEY);
    }

    @Override
    public Identity<FeeCalBillingSnapshotRecord, Long> getIdentity() {
        return Keys.IDENTITY_FEE_CAL_BILLING_SNAPSHOT;
    }

    @Override
    public UniqueKey<FeeCalBillingSnapshotRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_BILLING_SNAPSHOT_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalBillingSnapshotRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalBillingSnapshotRecord>>asList(Keys.KEY_FEE_CAL_BILLING_SNAPSHOT_PRIMARY);
    }

    @Override
    public FeeCalBillingSnapshot as(String alias) {
        return new FeeCalBillingSnapshot(DSL.name(alias), this);
    }

    @Override
    public FeeCalBillingSnapshot as(Name alias) {
        return new FeeCalBillingSnapshot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalBillingSnapshot rename(String name) {
        return new FeeCalBillingSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalBillingSnapshot rename(Name name) {
        return new FeeCalBillingSnapshot(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, BigDecimal, BigDecimal, BigDecimal, JSON, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
