/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables;


import com.merchant.dao.DefaultSchema;
import com.merchant.dao.Indexes;
import com.merchant.dao.Keys;
import com.merchant.dao.tables.records.FeeCalTermInstAllocRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 费用项账单分配
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermInstAlloc extends TableImpl<FeeCalTermInstAllocRecord> {

    private static final long serialVersionUID = 1614488544;

    /**
     * The reference instance of <code>fee_cal_term_inst_alloc</code>
     */
    public static final FeeCalTermInstAlloc FEE_CAL_TERM_INST_ALLOC = new FeeCalTermInstAlloc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeeCalTermInstAllocRecord> getRecordType() {
        return FeeCalTermInstAllocRecord.class;
    }

    /**
     * The column <code>fee_cal_term_inst_alloc.id</code>. 主键
     */
    public final TableField<FeeCalTermInstAllocRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>fee_cal_term_inst_alloc.batch_no</code>. 批次号
     */
    public final TableField<FeeCalTermInstAllocRecord, String> BATCH_NO = createField(DSL.name("batch_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "批次号");

    /**
     * The column <code>fee_cal_term_inst_alloc.term_inst_id</code>. 费用项实例ID
     */
    public final TableField<FeeCalTermInstAllocRecord, Long> TERM_INST_ID = createField(DSL.name("term_inst_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "费用项实例ID");

    /**
     * The column <code>fee_cal_term_inst_alloc.term_code</code>. 费用项编码
     */
    public final TableField<FeeCalTermInstAllocRecord, String> TERM_CODE = createField(DSL.name("term_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "费用项编码");

    /**
     * The column <code>fee_cal_term_inst_alloc.billing_snapshot_id</code>. 快照ID
     */
    public final TableField<FeeCalTermInstAllocRecord, Long> BILLING_SNAPSHOT_ID = createField(DSL.name("billing_snapshot_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "快照ID");

    /**
     * The column <code>fee_cal_term_inst_alloc.unpaid_amount</code>. 账单未付金额
     */
    public final TableField<FeeCalTermInstAllocRecord, BigDecimal> UNPAID_AMOUNT = createField(DSL.name("unpaid_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).nullable(false), this, "账单未付金额");

    /**
     * The column <code>fee_cal_term_inst_alloc.alloc_flag</code>. 是否抵扣
     */
    public final TableField<FeeCalTermInstAllocRecord, Integer> ALLOC_FLAG = createField(DSL.name("alloc_flag"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否抵扣");

    /**
     * The column <code>fee_cal_term_inst_alloc.alloc_amount</code>. 抵扣金额
     */
    public final TableField<FeeCalTermInstAllocRecord, BigDecimal> ALLOC_AMOUNT = createField(DSL.name("alloc_amount"), org.jooq.impl.SQLDataType.DECIMAL(18, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "抵扣金额");

    /**
     * The column <code>fee_cal_term_inst_alloc.created_at</code>.
     */
    public final TableField<FeeCalTermInstAllocRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fee_cal_term_inst_alloc.updated_at</code>.
     */
    public final TableField<FeeCalTermInstAllocRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>fee_cal_term_inst_alloc</code> table reference
     */
    public FeeCalTermInstAlloc() {
        this(DSL.name("fee_cal_term_inst_alloc"), null);
    }

    /**
     * Create an aliased <code>fee_cal_term_inst_alloc</code> table reference
     */
    public FeeCalTermInstAlloc(String alias) {
        this(DSL.name(alias), FEE_CAL_TERM_INST_ALLOC);
    }

    /**
     * Create an aliased <code>fee_cal_term_inst_alloc</code> table reference
     */
    public FeeCalTermInstAlloc(Name alias) {
        this(alias, FEE_CAL_TERM_INST_ALLOC);
    }

    private FeeCalTermInstAlloc(Name alias, Table<FeeCalTermInstAllocRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeeCalTermInstAlloc(Name alias, Table<FeeCalTermInstAllocRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("费用项账单分配"), TableOptions.table());
    }

    public <O extends Record> FeeCalTermInstAlloc(Table<O> child, ForeignKey<O, FeeCalTermInstAllocRecord> key) {
        super(child, key, FEE_CAL_TERM_INST_ALLOC);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FEE_CAL_TERM_INST_ALLOC_IDX_BATCH_TERM);
    }

    @Override
    public Identity<FeeCalTermInstAllocRecord, Long> getIdentity() {
        return Keys.IDENTITY_FEE_CAL_TERM_INST_ALLOC;
    }

    @Override
    public UniqueKey<FeeCalTermInstAllocRecord> getPrimaryKey() {
        return Keys.KEY_FEE_CAL_TERM_INST_ALLOC_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeeCalTermInstAllocRecord>> getKeys() {
        return Arrays.<UniqueKey<FeeCalTermInstAllocRecord>>asList(Keys.KEY_FEE_CAL_TERM_INST_ALLOC_PRIMARY, Keys.KEY_FEE_CAL_TERM_INST_ALLOC_UK_TERM_SNAPSHOT);
    }

    @Override
    public FeeCalTermInstAlloc as(String alias) {
        return new FeeCalTermInstAlloc(DSL.name(alias), this);
    }

    @Override
    public FeeCalTermInstAlloc as(Name alias) {
        return new FeeCalTermInstAlloc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalTermInstAlloc rename(String name) {
        return new FeeCalTermInstAlloc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeeCalTermInstAlloc rename(Name name) {
        return new FeeCalTermInstAlloc(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, Long, String, Long, BigDecimal, Integer, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
