/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 费用项账单分配
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermInstAllocEntity implements Serializable {

    private static final long serialVersionUID = 1304272885;

    private Long          id;
    private String        batchNo;
    private Long          termInstId;
    private String        termCode;
    private Long          billingSnapshotId;
    private BigDecimal    unpaidAmount;
    private Integer       allocFlag;
    private BigDecimal    allocAmount;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FeeCalTermInstAllocEntity() {}

    public FeeCalTermInstAllocEntity(FeeCalTermInstAllocEntity value) {
        this.id = value.id;
        this.batchNo = value.batchNo;
        this.termInstId = value.termInstId;
        this.termCode = value.termCode;
        this.billingSnapshotId = value.billingSnapshotId;
        this.unpaidAmount = value.unpaidAmount;
        this.allocFlag = value.allocFlag;
        this.allocAmount = value.allocAmount;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FeeCalTermInstAllocEntity(
        Long          id,
        String        batchNo,
        Long          termInstId,
        String        termCode,
        Long          billingSnapshotId,
        BigDecimal    unpaidAmount,
        Integer       allocFlag,
        BigDecimal    allocAmount,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.batchNo = batchNo;
        this.termInstId = termInstId;
        this.termCode = termCode;
        this.billingSnapshotId = billingSnapshotId;
        this.unpaidAmount = unpaidAmount;
        this.allocFlag = allocFlag;
        this.allocAmount = allocAmount;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public FeeCalTermInstAllocEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public FeeCalTermInstAllocEntity setBatchNo(String batchNo) {
        this.batchNo = batchNo;
        return this;
    }

    public Long getTermInstId() {
        return this.termInstId;
    }

    public FeeCalTermInstAllocEntity setTermInstId(Long termInstId) {
        this.termInstId = termInstId;
        return this;
    }

    public String getTermCode() {
        return this.termCode;
    }

    public FeeCalTermInstAllocEntity setTermCode(String termCode) {
        this.termCode = termCode;
        return this;
    }

    public Long getBillingSnapshotId() {
        return this.billingSnapshotId;
    }

    public FeeCalTermInstAllocEntity setBillingSnapshotId(Long billingSnapshotId) {
        this.billingSnapshotId = billingSnapshotId;
        return this;
    }

    public BigDecimal getUnpaidAmount() {
        return this.unpaidAmount;
    }

    public FeeCalTermInstAllocEntity setUnpaidAmount(BigDecimal unpaidAmount) {
        this.unpaidAmount = unpaidAmount;
        return this;
    }

    public Integer getAllocFlag() {
        return this.allocFlag;
    }

    public FeeCalTermInstAllocEntity setAllocFlag(Integer allocFlag) {
        this.allocFlag = allocFlag;
        return this;
    }

    public BigDecimal getAllocAmount() {
        return this.allocAmount;
    }

    public FeeCalTermInstAllocEntity setAllocAmount(BigDecimal allocAmount) {
        this.allocAmount = allocAmount;
        return this;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public FeeCalTermInstAllocEntity setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public FeeCalTermInstAllocEntity setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalTermInstAllocEntity (");

        sb.append(id);
        sb.append(", ").append(batchNo);
        sb.append(", ").append(termInstId);
        sb.append(", ").append(termCode);
        sb.append(", ").append(billingSnapshotId);
        sb.append(", ").append(unpaidAmount);
        sb.append(", ").append(allocFlag);
        sb.append(", ").append(allocAmount);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
