/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 费用清算批次表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalBatchEntity implements Serializable {

    private static final long serialVersionUID = 1816539945;

    private Long          id;
    private String        batchNo;
    private String        status;
    private String        billingDataStatus;
    private BigDecimal    depositBalanceTotal;
    private BigDecimal    depositAmountDeduct;
    private BigDecimal    depositBalanceRemain;
    private BigDecimal    unpaidAmountRemain;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public FeeCalBatchEntity() {}

    public FeeCalBatchEntity(FeeCalBatchEntity value) {
        this.id = value.id;
        this.batchNo = value.batchNo;
        this.status = value.status;
        this.billingDataStatus = value.billingDataStatus;
        this.depositBalanceTotal = value.depositBalanceTotal;
        this.depositAmountDeduct = value.depositAmountDeduct;
        this.depositBalanceRemain = value.depositBalanceRemain;
        this.unpaidAmountRemain = value.unpaidAmountRemain;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public FeeCalBatchEntity(
        Long          id,
        String        batchNo,
        String        status,
        String        billingDataStatus,
        BigDecimal    depositBalanceTotal,
        BigDecimal    depositAmountDeduct,
        BigDecimal    depositBalanceRemain,
        BigDecimal    unpaidAmountRemain,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.batchNo = batchNo;
        this.status = status;
        this.billingDataStatus = billingDataStatus;
        this.depositBalanceTotal = depositBalanceTotal;
        this.depositAmountDeduct = depositAmountDeduct;
        this.depositBalanceRemain = depositBalanceRemain;
        this.unpaidAmountRemain = unpaidAmountRemain;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public FeeCalBatchEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public FeeCalBatchEntity setBatchNo(String batchNo) {
        this.batchNo = batchNo;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public FeeCalBatchEntity setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getBillingDataStatus() {
        return this.billingDataStatus;
    }

    public FeeCalBatchEntity setBillingDataStatus(String billingDataStatus) {
        this.billingDataStatus = billingDataStatus;
        return this;
    }

    public BigDecimal getDepositBalanceTotal() {
        return this.depositBalanceTotal;
    }

    public FeeCalBatchEntity setDepositBalanceTotal(BigDecimal depositBalanceTotal) {
        this.depositBalanceTotal = depositBalanceTotal;
        return this;
    }

    public BigDecimal getDepositAmountDeduct() {
        return this.depositAmountDeduct;
    }

    public FeeCalBatchEntity setDepositAmountDeduct(BigDecimal depositAmountDeduct) {
        this.depositAmountDeduct = depositAmountDeduct;
        return this;
    }

    public BigDecimal getDepositBalanceRemain() {
        return this.depositBalanceRemain;
    }

    public FeeCalBatchEntity setDepositBalanceRemain(BigDecimal depositBalanceRemain) {
        this.depositBalanceRemain = depositBalanceRemain;
        return this;
    }

    public BigDecimal getUnpaidAmountRemain() {
        return this.unpaidAmountRemain;
    }

    public FeeCalBatchEntity setUnpaidAmountRemain(BigDecimal unpaidAmountRemain) {
        this.unpaidAmountRemain = unpaidAmountRemain;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public FeeCalBatchEntity setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public FeeCalBatchEntity setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalBatchEntity (");

        sb.append(id);
        sb.append(", ").append(batchNo);
        sb.append(", ").append(status);
        sb.append(", ").append(billingDataStatus);
        sb.append(", ").append(depositBalanceTotal);
        sb.append(", ").append(depositAmountDeduct);
        sb.append(", ").append(depositBalanceRemain);
        sb.append(", ").append(unpaidAmountRemain);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
