/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.JSON;


/**
 * 资金指令表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalFundInstructionEntity implements Serializable {

    private static final long serialVersionUID = -926748855;

    private Long          id;
    private String        batchNo;
    private Long          termInstId;
    private String        settleSubjectType;
    private String        settleSubjectNo;
    private String        payerType;
    private String        payerNo;
    private String        payeeType;
    private String        payeeNo;
    private String        fundDirection;
    private String        fundBizType;
    private String        accountType;
    private BigDecimal    shouldAmount;
    private BigDecimal    actualAmount;
    private String        fundStatus;
    private String        callbackStatus;
    private String        fundOrderId;
    private String        fundChannel;
    private JSON          fundOrderInfo;
    private String        attachmentIds;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FeeCalFundInstructionEntity() {}

    public FeeCalFundInstructionEntity(FeeCalFundInstructionEntity value) {
        this.id = value.id;
        this.batchNo = value.batchNo;
        this.termInstId = value.termInstId;
        this.settleSubjectType = value.settleSubjectType;
        this.settleSubjectNo = value.settleSubjectNo;
        this.payerType = value.payerType;
        this.payerNo = value.payerNo;
        this.payeeType = value.payeeType;
        this.payeeNo = value.payeeNo;
        this.fundDirection = value.fundDirection;
        this.fundBizType = value.fundBizType;
        this.accountType = value.accountType;
        this.shouldAmount = value.shouldAmount;
        this.actualAmount = value.actualAmount;
        this.fundStatus = value.fundStatus;
        this.callbackStatus = value.callbackStatus;
        this.fundOrderId = value.fundOrderId;
        this.fundChannel = value.fundChannel;
        this.fundOrderInfo = value.fundOrderInfo;
        this.attachmentIds = value.attachmentIds;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FeeCalFundInstructionEntity(
        Long          id,
        String        batchNo,
        Long          termInstId,
        String        settleSubjectType,
        String        settleSubjectNo,
        String        payerType,
        String        payerNo,
        String        payeeType,
        String        payeeNo,
        String        fundDirection,
        String        fundBizType,
        String        accountType,
        BigDecimal    shouldAmount,
        BigDecimal    actualAmount,
        String        fundStatus,
        String        callbackStatus,
        String        fundOrderId,
        String        fundChannel,
        JSON          fundOrderInfo,
        String        attachmentIds,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.batchNo = batchNo;
        this.termInstId = termInstId;
        this.settleSubjectType = settleSubjectType;
        this.settleSubjectNo = settleSubjectNo;
        this.payerType = payerType;
        this.payerNo = payerNo;
        this.payeeType = payeeType;
        this.payeeNo = payeeNo;
        this.fundDirection = fundDirection;
        this.fundBizType = fundBizType;
        this.accountType = accountType;
        this.shouldAmount = shouldAmount;
        this.actualAmount = actualAmount;
        this.fundStatus = fundStatus;
        this.callbackStatus = callbackStatus;
        this.fundOrderId = fundOrderId;
        this.fundChannel = fundChannel;
        this.fundOrderInfo = fundOrderInfo;
        this.attachmentIds = attachmentIds;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public FeeCalFundInstructionEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public FeeCalFundInstructionEntity setBatchNo(String batchNo) {
        this.batchNo = batchNo;
        return this;
    }

    public Long getTermInstId() {
        return this.termInstId;
    }

    public FeeCalFundInstructionEntity setTermInstId(Long termInstId) {
        this.termInstId = termInstId;
        return this;
    }

    public String getSettleSubjectType() {
        return this.settleSubjectType;
    }

    public FeeCalFundInstructionEntity setSettleSubjectType(String settleSubjectType) {
        this.settleSubjectType = settleSubjectType;
        return this;
    }

    public String getSettleSubjectNo() {
        return this.settleSubjectNo;
    }

    public FeeCalFundInstructionEntity setSettleSubjectNo(String settleSubjectNo) {
        this.settleSubjectNo = settleSubjectNo;
        return this;
    }

    public String getPayerType() {
        return this.payerType;
    }

    public FeeCalFundInstructionEntity setPayerType(String payerType) {
        this.payerType = payerType;
        return this;
    }

    public String getPayerNo() {
        return this.payerNo;
    }

    public FeeCalFundInstructionEntity setPayerNo(String payerNo) {
        this.payerNo = payerNo;
        return this;
    }

    public String getPayeeType() {
        return this.payeeType;
    }

    public FeeCalFundInstructionEntity setPayeeType(String payeeType) {
        this.payeeType = payeeType;
        return this;
    }

    public String getPayeeNo() {
        return this.payeeNo;
    }

    public FeeCalFundInstructionEntity setPayeeNo(String payeeNo) {
        this.payeeNo = payeeNo;
        return this;
    }

    public String getFundDirection() {
        return this.fundDirection;
    }

    public FeeCalFundInstructionEntity setFundDirection(String fundDirection) {
        this.fundDirection = fundDirection;
        return this;
    }

    public String getFundBizType() {
        return this.fundBizType;
    }

    public FeeCalFundInstructionEntity setFundBizType(String fundBizType) {
        this.fundBizType = fundBizType;
        return this;
    }

    public String getAccountType() {
        return this.accountType;
    }

    public FeeCalFundInstructionEntity setAccountType(String accountType) {
        this.accountType = accountType;
        return this;
    }

    public BigDecimal getShouldAmount() {
        return this.shouldAmount;
    }

    public FeeCalFundInstructionEntity setShouldAmount(BigDecimal shouldAmount) {
        this.shouldAmount = shouldAmount;
        return this;
    }

    public BigDecimal getActualAmount() {
        return this.actualAmount;
    }

    public FeeCalFundInstructionEntity setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
        return this;
    }

    public String getFundStatus() {
        return this.fundStatus;
    }

    public FeeCalFundInstructionEntity setFundStatus(String fundStatus) {
        this.fundStatus = fundStatus;
        return this;
    }

    public String getCallbackStatus() {
        return this.callbackStatus;
    }

    public FeeCalFundInstructionEntity setCallbackStatus(String callbackStatus) {
        this.callbackStatus = callbackStatus;
        return this;
    }

    public String getFundOrderId() {
        return this.fundOrderId;
    }

    public FeeCalFundInstructionEntity setFundOrderId(String fundOrderId) {
        this.fundOrderId = fundOrderId;
        return this;
    }

    public String getFundChannel() {
        return this.fundChannel;
    }

    public FeeCalFundInstructionEntity setFundChannel(String fundChannel) {
        this.fundChannel = fundChannel;
        return this;
    }

    public JSON getFundOrderInfo() {
        return this.fundOrderInfo;
    }

    public FeeCalFundInstructionEntity setFundOrderInfo(JSON fundOrderInfo) {
        this.fundOrderInfo = fundOrderInfo;
        return this;
    }

    public String getAttachmentIds() {
        return this.attachmentIds;
    }

    public FeeCalFundInstructionEntity setAttachmentIds(String attachmentIds) {
        this.attachmentIds = attachmentIds;
        return this;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public FeeCalFundInstructionEntity setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public FeeCalFundInstructionEntity setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalFundInstructionEntity (");

        sb.append(id);
        sb.append(", ").append(batchNo);
        sb.append(", ").append(termInstId);
        sb.append(", ").append(settleSubjectType);
        sb.append(", ").append(settleSubjectNo);
        sb.append(", ").append(payerType);
        sb.append(", ").append(payerNo);
        sb.append(", ").append(payeeType);
        sb.append(", ").append(payeeNo);
        sb.append(", ").append(fundDirection);
        sb.append(", ").append(fundBizType);
        sb.append(", ").append(accountType);
        sb.append(", ").append(shouldAmount);
        sb.append(", ").append(actualAmount);
        sb.append(", ").append(fundStatus);
        sb.append(", ").append(callbackStatus);
        sb.append(", ").append(fundOrderId);
        sb.append(", ").append(fundChannel);
        sb.append(", ").append(fundOrderInfo);
        sb.append(", ").append(attachmentIds);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
