/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.JSON;


/**
 * 清算账单视图快照
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalBillingSnapshotEntity implements Serializable {

    private static final long serialVersionUID = 1495929223;

    private Long          id;
    private String        batchNo;
    private String        termCode;
    private String        billingKey;
    private BigDecimal    billingShouldPayAmount;
    private BigDecimal    billingActualPayAmount;
    private BigDecimal    billingUnpaidAmount;
    private JSON          billingSourceInfo;
    private LocalDateTime snapshotTime;

    public FeeCalBillingSnapshotEntity() {}

    public FeeCalBillingSnapshotEntity(FeeCalBillingSnapshotEntity value) {
        this.id = value.id;
        this.batchNo = value.batchNo;
        this.termCode = value.termCode;
        this.billingKey = value.billingKey;
        this.billingShouldPayAmount = value.billingShouldPayAmount;
        this.billingActualPayAmount = value.billingActualPayAmount;
        this.billingUnpaidAmount = value.billingUnpaidAmount;
        this.billingSourceInfo = value.billingSourceInfo;
        this.snapshotTime = value.snapshotTime;
    }

    public FeeCalBillingSnapshotEntity(
        Long          id,
        String        batchNo,
        String        termCode,
        String        billingKey,
        BigDecimal    billingShouldPayAmount,
        BigDecimal    billingActualPayAmount,
        BigDecimal    billingUnpaidAmount,
        JSON          billingSourceInfo,
        LocalDateTime snapshotTime
    ) {
        this.id = id;
        this.batchNo = batchNo;
        this.termCode = termCode;
        this.billingKey = billingKey;
        this.billingShouldPayAmount = billingShouldPayAmount;
        this.billingActualPayAmount = billingActualPayAmount;
        this.billingUnpaidAmount = billingUnpaidAmount;
        this.billingSourceInfo = billingSourceInfo;
        this.snapshotTime = snapshotTime;
    }

    public Long getId() {
        return this.id;
    }

    public FeeCalBillingSnapshotEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public FeeCalBillingSnapshotEntity setBatchNo(String batchNo) {
        this.batchNo = batchNo;
        return this;
    }

    public String getTermCode() {
        return this.termCode;
    }

    public FeeCalBillingSnapshotEntity setTermCode(String termCode) {
        this.termCode = termCode;
        return this;
    }

    public String getBillingKey() {
        return this.billingKey;
    }

    public FeeCalBillingSnapshotEntity setBillingKey(String billingKey) {
        this.billingKey = billingKey;
        return this;
    }

    public BigDecimal getBillingShouldPayAmount() {
        return this.billingShouldPayAmount;
    }

    public FeeCalBillingSnapshotEntity setBillingShouldPayAmount(BigDecimal billingShouldPayAmount) {
        this.billingShouldPayAmount = billingShouldPayAmount;
        return this;
    }

    public BigDecimal getBillingActualPayAmount() {
        return this.billingActualPayAmount;
    }

    public FeeCalBillingSnapshotEntity setBillingActualPayAmount(BigDecimal billingActualPayAmount) {
        this.billingActualPayAmount = billingActualPayAmount;
        return this;
    }

    public BigDecimal getBillingUnpaidAmount() {
        return this.billingUnpaidAmount;
    }

    public FeeCalBillingSnapshotEntity setBillingUnpaidAmount(BigDecimal billingUnpaidAmount) {
        this.billingUnpaidAmount = billingUnpaidAmount;
        return this;
    }

    public JSON getBillingSourceInfo() {
        return this.billingSourceInfo;
    }

    public FeeCalBillingSnapshotEntity setBillingSourceInfo(JSON billingSourceInfo) {
        this.billingSourceInfo = billingSourceInfo;
        return this;
    }

    public LocalDateTime getSnapshotTime() {
        return this.snapshotTime;
    }

    public FeeCalBillingSnapshotEntity setSnapshotTime(LocalDateTime snapshotTime) {
        this.snapshotTime = snapshotTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalBillingSnapshotEntity (");

        sb.append(id);
        sb.append(", ").append(batchNo);
        sb.append(", ").append(termCode);
        sb.append(", ").append(billingKey);
        sb.append(", ").append(billingShouldPayAmount);
        sb.append(", ").append(billingActualPayAmount);
        sb.append(", ").append(billingUnpaidAmount);
        sb.append(", ").append(billingSourceInfo);
        sb.append(", ").append(snapshotTime);

        sb.append(")");
        return sb.toString();
    }
}
