/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 费用项定义表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermDefEntity implements Serializable {

    private static final long serialVersionUID = -1109368617;

    private String        code;
    private String        name;
    private Integer       sortNo;
    private Byte          enabled;
    private Byte          autoLoad;
    private Integer       billAllocEnabled;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public FeeCalTermDefEntity() {}

    public FeeCalTermDefEntity(FeeCalTermDefEntity value) {
        this.code = value.code;
        this.name = value.name;
        this.sortNo = value.sortNo;
        this.enabled = value.enabled;
        this.autoLoad = value.autoLoad;
        this.billAllocEnabled = value.billAllocEnabled;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public FeeCalTermDefEntity(
        String        code,
        String        name,
        Integer       sortNo,
        Byte          enabled,
        Byte          autoLoad,
        Integer       billAllocEnabled,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.code = code;
        this.name = name;
        this.sortNo = sortNo;
        this.enabled = enabled;
        this.autoLoad = autoLoad;
        this.billAllocEnabled = billAllocEnabled;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public String getCode() {
        return this.code;
    }

    public FeeCalTermDefEntity setCode(String code) {
        this.code = code;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public FeeCalTermDefEntity setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getSortNo() {
        return this.sortNo;
    }

    public FeeCalTermDefEntity setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
        return this;
    }

    public Byte getEnabled() {
        return this.enabled;
    }

    public FeeCalTermDefEntity setEnabled(Byte enabled) {
        this.enabled = enabled;
        return this;
    }

    public Byte getAutoLoad() {
        return this.autoLoad;
    }

    public FeeCalTermDefEntity setAutoLoad(Byte autoLoad) {
        this.autoLoad = autoLoad;
        return this;
    }

    public Integer getBillAllocEnabled() {
        return this.billAllocEnabled;
    }

    public FeeCalTermDefEntity setBillAllocEnabled(Integer billAllocEnabled) {
        this.billAllocEnabled = billAllocEnabled;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public FeeCalTermDefEntity setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public FeeCalTermDefEntity setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalTermDefEntity (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(sortNo);
        sb.append(", ").append(enabled);
        sb.append(", ").append(autoLoad);
        sb.append(", ").append(billAllocEnabled);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
