/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 费用项实例表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalTermInstEntity implements Serializable {

    private static final long serialVersionUID = -1751095699;

    private Long          id;
    private String        batchNo;
    private Long          merchantId;
    private String        termCode;
    private String        status;
    private BigDecimal    unpaidAmount;
    private Byte          deductFlag;
    private BigDecimal    deductAmount;
    private Byte          autoLoad;
    private Integer       billingAllocEnabled;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public FeeCalTermInstEntity() {}

    public FeeCalTermInstEntity(FeeCalTermInstEntity value) {
        this.id = value.id;
        this.batchNo = value.batchNo;
        this.merchantId = value.merchantId;
        this.termCode = value.termCode;
        this.status = value.status;
        this.unpaidAmount = value.unpaidAmount;
        this.deductFlag = value.deductFlag;
        this.deductAmount = value.deductAmount;
        this.autoLoad = value.autoLoad;
        this.billingAllocEnabled = value.billingAllocEnabled;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public FeeCalTermInstEntity(
        Long          id,
        String        batchNo,
        Long          merchantId,
        String        termCode,
        String        status,
        BigDecimal    unpaidAmount,
        Byte          deductFlag,
        BigDecimal    deductAmount,
        Byte          autoLoad,
        Integer       billingAllocEnabled,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.batchNo = batchNo;
        this.merchantId = merchantId;
        this.termCode = termCode;
        this.status = status;
        this.unpaidAmount = unpaidAmount;
        this.deductFlag = deductFlag;
        this.deductAmount = deductAmount;
        this.autoLoad = autoLoad;
        this.billingAllocEnabled = billingAllocEnabled;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public FeeCalTermInstEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public FeeCalTermInstEntity setBatchNo(String batchNo) {
        this.batchNo = batchNo;
        return this;
    }

    public Long getMerchantId() {
        return this.merchantId;
    }

    public FeeCalTermInstEntity setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
        return this;
    }

    public String getTermCode() {
        return this.termCode;
    }

    public FeeCalTermInstEntity setTermCode(String termCode) {
        this.termCode = termCode;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public FeeCalTermInstEntity setStatus(String status) {
        this.status = status;
        return this;
    }

    public BigDecimal getUnpaidAmount() {
        return this.unpaidAmount;
    }

    public FeeCalTermInstEntity setUnpaidAmount(BigDecimal unpaidAmount) {
        this.unpaidAmount = unpaidAmount;
        return this;
    }

    public Byte getDeductFlag() {
        return this.deductFlag;
    }

    public FeeCalTermInstEntity setDeductFlag(Byte deductFlag) {
        this.deductFlag = deductFlag;
        return this;
    }

    public BigDecimal getDeductAmount() {
        return this.deductAmount;
    }

    public FeeCalTermInstEntity setDeductAmount(BigDecimal deductAmount) {
        this.deductAmount = deductAmount;
        return this;
    }

    public Byte getAutoLoad() {
        return this.autoLoad;
    }

    public FeeCalTermInstEntity setAutoLoad(Byte autoLoad) {
        this.autoLoad = autoLoad;
        return this;
    }

    public Integer getBillingAllocEnabled() {
        return this.billingAllocEnabled;
    }

    public FeeCalTermInstEntity setBillingAllocEnabled(Integer billingAllocEnabled) {
        this.billingAllocEnabled = billingAllocEnabled;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public FeeCalTermInstEntity setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public FeeCalTermInstEntity setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalTermInstEntity (");

        sb.append(id);
        sb.append(", ").append(batchNo);
        sb.append(", ").append(merchantId);
        sb.append(", ").append(termCode);
        sb.append(", ").append(status);
        sb.append(", ").append(unpaidAmount);
        sb.append(", ").append(deductFlag);
        sb.append(", ").append(deductAmount);
        sb.append(", ").append(autoLoad);
        sb.append(", ").append(billingAllocEnabled);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
