/*
 * This file is generated by jOOQ.
 */
package com.merchant.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 清算主体表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCalMerchantEntity implements Serializable {

    private static final long serialVersionUID = 474076717;

    private Long          id;
    private String        batchNo;
    private String        merchantType;
    private String        merchantCode;
    private String        depositAccountId;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public FeeCalMerchantEntity() {}

    public FeeCalMerchantEntity(FeeCalMerchantEntity value) {
        this.id = value.id;
        this.batchNo = value.batchNo;
        this.merchantType = value.merchantType;
        this.merchantCode = value.merchantCode;
        this.depositAccountId = value.depositAccountId;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public FeeCalMerchantEntity(
        Long          id,
        String        batchNo,
        String        merchantType,
        String        merchantCode,
        String        depositAccountId,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.batchNo = batchNo;
        this.merchantType = merchantType;
        this.merchantCode = merchantCode;
        this.depositAccountId = depositAccountId;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public FeeCalMerchantEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public FeeCalMerchantEntity setBatchNo(String batchNo) {
        this.batchNo = batchNo;
        return this;
    }

    public String getMerchantType() {
        return this.merchantType;
    }

    public FeeCalMerchantEntity setMerchantType(String merchantType) {
        this.merchantType = merchantType;
        return this;
    }

    public String getMerchantCode() {
        return this.merchantCode;
    }

    public FeeCalMerchantEntity setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
        return this;
    }

    public String getDepositAccountId() {
        return this.depositAccountId;
    }

    public FeeCalMerchantEntity setDepositAccountId(String depositAccountId) {
        this.depositAccountId = depositAccountId;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public FeeCalMerchantEntity setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public FeeCalMerchantEntity setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCalMerchantEntity (");

        sb.append(id);
        sb.append(", ").append(batchNo);
        sb.append(", ").append(merchantType);
        sb.append(", ").append(merchantCode);
        sb.append(", ").append(depositAccountId);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
